import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
    extend: {
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', '-apple-system', 'Segoe UI', 'Roboto', 'sans-serif'],
        display: ['"Plus Jakarta Sans"', 'Inter', 'ui-sans-serif', 'system-ui'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'SFMono-Regular', 'monospace'],
      },
      colors: {
        border: "hsl(var(--border))",
        "border-strong": "hsl(var(--border-strong))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        surface: {
          DEFAULT: "hsl(var(--surface))",
          elevated: "hsl(var(--surface-elevated))",
          sunken: "hsl(var(--surface-sunken))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
          hover: "hsl(var(--primary-hover))",
          soft: "hsl(var(--primary-soft))",
          glow: "hsl(var(--primary-glow))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
          hover: "hsl(var(--accent-hover))",
          soft: "hsl(var(--accent-soft))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        success: {
          DEFAULT: "hsl(var(--success))",
          foreground: "hsl(var(--success-foreground))",
          soft: "hsl(var(--success-soft))",
        },
        warning: {
          DEFAULT: "hsl(var(--warning))",
          foreground: "hsl(var(--warning-foreground))",
          soft: "hsl(var(--warning-soft))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
          soft: "hsl(var(--destructive-soft))",
        },
        info: {
          DEFAULT: "hsl(var(--info))",
          foreground: "hsl(var(--info-foreground))",
          soft: "hsl(var(--info-soft))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          muted: "hsl(var(--sidebar-muted))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      backgroundImage: {
        "gradient-primary": "var(--gradient-primary)",
        "gradient-accent": "var(--gradient-accent)",
        "gradient-surface": "var(--gradient-surface)",
        "gradient-hero": "var(--gradient-hero)",
        "gradient-mesh": "var(--gradient-mesh)",
      },
      boxShadow: {
        xs: "var(--shadow-xs)",
        sm: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        xl: "var(--shadow-xl)",
        glow: "var(--shadow-glow)",
        "accent-glow": "var(--shadow-accent-glow)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xl: "calc(var(--radius) + 4px)",
        "2xl": "calc(var(--radius) + 8px)",
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "fade-in": { "0%": { opacity: "0", transform: "translateY(4px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
        "slide-in-right": { "0%": { opacity: "0", transform: "translateX(12px)" }, "100%": { opacity: "1", transform: "translateX(0)" } },
        "pulse-soft": { "0%, 100%": { opacity: "1" }, "50%": { opacity: "0.65" } },
        // — micro-interações do sistema de Chamados —
        "pop": { "0%": { transform: "scale(0.85)" }, "60%": { transform: "scale(1.12)" }, "100%": { transform: "scale(1)" } },
        "check-pop": { "0%": { transform: "scale(0) rotate(-20deg)", opacity: "0" }, "60%": { transform: "scale(1.25) rotate(6deg)" }, "100%": { transform: "scale(1) rotate(0)", opacity: "1" } },
        "star-pop": { "0%": { transform: "scale(0.6)" }, "45%": { transform: "scale(1.4)" }, "100%": { transform: "scale(1)" } },
        "shake": { "0%,100%": { transform: "translateX(0)" }, "20%,60%": { transform: "translateX(-5px)" }, "40%,80%": { transform: "translateX(5px)" } },
        "status-flash": { "0%": { boxShadow: "0 0 0 0 hsl(var(--primary) / 0.55)" }, "100%": { boxShadow: "0 0 0 10px hsl(var(--primary) / 0)" } },
        "rise-in": { "0%": { opacity: "0", transform: "translateY(10px) scale(0.98)" }, "100%": { opacity: "1", transform: "translateY(0) scale(1)" } },
        // — painéis de TV (Dashboard de Chamados): animações ambientes, que
        //   rodam sozinhas em loop porque não existe mouse na frente da tela —
        "orb-drift": { "0%, 100%": { transform: "translate(0, 0) scale(1)" }, "50%": { transform: "translate(-26px, 24px) scale(1.08)" } },
        "shine": { "0%": { backgroundPosition: "190% 0" }, "55%, 100%": { backgroundPosition: "-90% 0" } },
        "float-soft": { "0%, 100%": { transform: "translateY(0)" }, "50%": { transform: "translateY(-6px)" } },
        "ring-pulse": { "0%, 100%": { transform: "scale(1)", opacity: "0.7" }, "50%": { transform: "scale(1.06)", opacity: "1" } },
        "progress-fill": { "0%": { width: "0%" }, "100%": { width: "100%" } },
        // Reflexo percorrendo a trilha do Fluxo de Aprovação (snake): "-y" nos trechos
        // verticais (virada de linha), "-x" nos trechos horizontais.
        "flow-glow-y": { "0%": { backgroundPositionY: "-160%" }, "100%": { backgroundPositionY: "260%" } },
        "flow-glow-x": { "0%": { backgroundPositionX: "-160%" }, "100%": { backgroundPositionX: "260%" } },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.35s cubic-bezier(0.16, 1, 0.3, 1)",
        "slide-in-right": "slide-in-right 0.35s cubic-bezier(0.16, 1, 0.3, 1)",
        "pulse-soft": "pulse-soft 2.5s ease-in-out infinite",
        "pop": "pop 0.28s cubic-bezier(0.34, 1.56, 0.64, 1)",
        "check-pop": "check-pop 0.45s cubic-bezier(0.34, 1.56, 0.64, 1)",
        "star-pop": "star-pop 0.4s cubic-bezier(0.34, 1.56, 0.64, 1)",
        "shake": "shake 0.4s ease-in-out",
        "status-flash": "status-flash 0.7s ease-out",
        "rise-in": "rise-in 0.4s cubic-bezier(0.16, 1, 0.3, 1) both",
        "orb-drift": "orb-drift 22s ease-in-out infinite",
        "shine": "shine 7s cubic-bezier(0.16, 1, 0.3, 1) infinite",
        "float-soft": "float-soft 5s ease-in-out infinite",
        "ring-pulse": "ring-pulse 3.5s ease-in-out infinite",
        // 15s = ROTACAO_MS do Dashboard de Chamados (mantenha os dois iguais).
        "progress-fill": "progress-fill 15s linear forwards",
        "flow-glow-y": "flow-glow-y 4.5s linear infinite",
        "flow-glow-x": "flow-glow-x 4.5s linear infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate"), require("@tailwindcss/typography")],
} satisfies Config;
