-- =========================================================================
-- BI › ESTÚDIO — painéis e gráficos criados pelo analista de dados, à mão
-- (SQL) ou por texto (IA)
--
-- Pedido do Pablo em 14/09/2026: "módulo completo de B.I e integra uma I.A
-- pra criar B.I por textos, o Analista de Dados tem que conseguir criar B.I
-- do jeito que ele quiser, com gráficos da forma que ele quiser".
--
-- O DESENHO
--   BI_PAINEL   um painel = uma tela; tem dono, pode ser público (quem tem
--               o menu vê) ou privado (só o dono), e uma lista de FILTROS
--               (jsonb) que viram controles no topo — data, texto, lista.
--   BI_WIDGET   um gráfico/KPI/tabela do painel. O dado vem de um SELECT
--               escrito pelo analista (ou pela IA); a forma vem de `config`
--               (eixo, séries, formato). Os filtros do painel entram no SQL
--               como {{chave}} e são substituídos com quote_literal — nunca
--               por concatenação.
--   BI_IA_LOG   cada pedido à IA fica registrado (quem, o texto, o que ela
--               devolveu) — auditoria e material pra melhorar o prompt.
--
-- QUEM RODA O SQL — e como isso não vira um buraco
--   bi_executar_sql(p_sql, p_params)   → livre, só pra quem tem 'alterar'
--                                        (o analista, no editor)
--   bi_widget_dados(p_widget_id, ...)  → roda o SQL GRAVADO no widget, pra
--                                        quem pode ver o painel (viewer não
--                                        escreve SQL nenhum)
--   Os dois passam por bi_sql_seguro(): só SELECT/WITH, uma instrução, sem
--   auth/storage/vault/pg_catalog, sem tabelas da lista bloqueada (senha,
--   token, denúncia do canal de ética...), transação READ ONLY, timeout de
--   20 s, teto de 5.000 linhas. SECURITY DEFINER de propósito: o analista
--   precisa enxergar o dado inteiro pra montar BI — a RLS de cada tela não
--   é o recorte certo aqui; o recorte é o menu 'bi_estudio' + a ação.
--
-- Menus (README: toda tela nova ganha 1 linha em app_menu):
--   bi_estudio     /app/bi/estudio    visualizar (vê painéis públicos),
--                                     incluir/alterar/excluir (o analista),
--                                     executar_ia (pode pedir pra IA)
--
-- Idempotente. Aplicar no banco do app.
-- =========================================================================

-- ── 1) Menu e ações ─────────────────────────────────────────────────────
INSERT INTO public.app_menu (modulo_id, codigo, nome, rota, ordem, ativo)
SELECT m.id, 'bi_estudio', 'Estúdio de BI', '/app/bi/estudio', 20, true
  FROM public.app_modulo m
 WHERE m.codigo = 'bi'
ON CONFLICT (modulo_id, codigo) DO NOTHING;

INSERT INTO public.app_menu_acao (menu_codigo, acao)
VALUES
  ('bi_estudio', 'visualizar'::app_acao),
  ('bi_estudio', 'incluir'::app_acao),
  ('bi_estudio', 'alterar'::app_acao),
  ('bi_estudio', 'excluir'::app_acao),
  ('bi_estudio', 'executar_ia'::app_acao),
  ('bi_estudio', 'exportar'::app_acao)
ON CONFLICT (menu_codigo, acao) DO NOTHING;

-- ── 2) Tabelas ───────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public."BI_PAINEL" (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome          text NOT NULL,
  descricao     text,
  dono_id       uuid NOT NULL DEFAULT auth.uid(),
  dono_nome     text,
  publico       boolean NOT NULL DEFAULT false,
  -- [{chave, rotulo, tipo: 'texto'|'data'|'numero'|'lista', padrao, opcoes: [..], opcoes_sql}]
  filtros       jsonb NOT NULL DEFAULT '[]'::jsonb,
  -- {tema: 'claro'|'escuro', colunas: 12, atualizar_a_cada_seg?: number}
  config        jsonb NOT NULL DEFAULT '{}'::jsonb,
  criado_em     timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public."BI_WIDGET" (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  painel_id     bigint NOT NULL REFERENCES public."BI_PAINEL"(id) ON DELETE CASCADE,
  titulo        text NOT NULL,
  subtitulo     text,
  -- kpi | barras | barras_h | barras_empilhadas | linha | area | pizza | rosca | dispersao | tabela
  tipo          text NOT NULL DEFAULT 'barras',
  sql           text NOT NULL,
  -- {x, series: [{coluna, rotulo, cor}], formato: 'numero'|'moeda'|'percentual'|'inteiro',
  --  casas, mostrar_rotulos, ordenar, limite, kpi: {coluna, comparar_coluna, sufixo}, ...}
  config        jsonb NOT NULL DEFAULT '{}'::jsonb,
  largura       int  NOT NULL DEFAULT 6  CHECK (largura BETWEEN 3 AND 12),
  altura        int  NOT NULL DEFAULT 2  CHECK (altura  BETWEEN 1 AND 4),
  ordem         int  NOT NULL DEFAULT 0,
  criado_por_ia boolean NOT NULL DEFAULT false,
  criado_em     timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_bi_widget_painel ON public."BI_WIDGET"(painel_id, ordem);

CREATE TABLE IF NOT EXISTS public."BI_IA_LOG" (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     uuid DEFAULT auth.uid(),
  painel_id   bigint,
  pedido      text NOT NULL,
  resposta    jsonb,
  erro        text,
  modelo      text,
  duracao_ms  int,
  criado_em   timestamptz NOT NULL DEFAULT now()
);

-- set_updated_at() escreve em updated_at; estas tabelas são em português.
CREATE OR REPLACE FUNCTION public.bi_set_atualizado_em()
RETURNS trigger LANGUAGE plpgsql SET search_path = public, pg_temp AS $fn$
BEGIN NEW.atualizado_em := now(); RETURN NEW; END $fn$;
DROP TRIGGER IF EXISTS trg_bi_painel_updated ON public."BI_PAINEL";
CREATE TRIGGER trg_bi_painel_updated BEFORE UPDATE ON public."BI_PAINEL"
  FOR EACH ROW EXECUTE FUNCTION public.bi_set_atualizado_em();
DROP TRIGGER IF EXISTS trg_bi_widget_updated ON public."BI_WIDGET";
CREATE TRIGGER trg_bi_widget_updated BEFORE UPDATE ON public."BI_WIDGET"
  FOR EACH ROW EXECUTE FUNCTION public.bi_set_atualizado_em();

GRANT SELECT, INSERT, UPDATE, DELETE ON public."BI_PAINEL", public."BI_WIDGET", public."BI_IA_LOG" TO authenticated;

-- ── 3) RLS ───────────────────────────────────────────────────────────────
ALTER TABLE public."BI_PAINEL"  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."BI_WIDGET"  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."BI_IA_LOG"  ENABLE ROW LEVEL SECURITY;

-- Vê: dono, ou público + menu. Edita: dono, ou 'alterar' (o analista pode
-- mexer em painel público de outro — o Estúdio é compartilhado por desenho).
DROP POLICY IF EXISTS bi_painel_select ON public."BI_PAINEL";
CREATE POLICY bi_painel_select ON public."BI_PAINEL" FOR SELECT TO authenticated
  USING (dono_id = auth.uid()
         OR (publico AND public.has_screen_access(auth.uid(), 'bi_estudio', 'visualizar'::app_acao)));
DROP POLICY IF EXISTS bi_painel_insert ON public."BI_PAINEL";
CREATE POLICY bi_painel_insert ON public."BI_PAINEL" FOR INSERT TO authenticated
  WITH CHECK (public.has_screen_access(auth.uid(), 'bi_estudio', 'incluir'::app_acao));
DROP POLICY IF EXISTS bi_painel_update ON public."BI_PAINEL";
CREATE POLICY bi_painel_update ON public."BI_PAINEL" FOR UPDATE TO authenticated
  USING (dono_id = auth.uid() OR public.has_screen_access(auth.uid(), 'bi_estudio', 'alterar'::app_acao))
  WITH CHECK (dono_id = auth.uid() OR public.has_screen_access(auth.uid(), 'bi_estudio', 'alterar'::app_acao));
DROP POLICY IF EXISTS bi_painel_delete ON public."BI_PAINEL";
CREATE POLICY bi_painel_delete ON public."BI_PAINEL" FOR DELETE TO authenticated
  USING (dono_id = auth.uid() OR public.has_screen_access(auth.uid(), 'bi_estudio', 'excluir'::app_acao));

-- Widget segue o painel.
DROP POLICY IF EXISTS bi_widget_select ON public."BI_WIDGET";
CREATE POLICY bi_widget_select ON public."BI_WIDGET" FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM public."BI_PAINEL" p WHERE p.id = painel_id));
DROP POLICY IF EXISTS bi_widget_write ON public."BI_WIDGET";
CREATE POLICY bi_widget_write ON public."BI_WIDGET" FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM public."BI_PAINEL" p WHERE p.id = painel_id
                   AND (p.dono_id = auth.uid() OR public.has_screen_access(auth.uid(), 'bi_estudio', 'alterar'::app_acao))))
  WITH CHECK (EXISTS (SELECT 1 FROM public."BI_PAINEL" p WHERE p.id = painel_id
                   AND (p.dono_id = auth.uid() OR public.has_screen_access(auth.uid(), 'bi_estudio', 'alterar'::app_acao))));

DROP POLICY IF EXISTS bi_ia_log_select ON public."BI_IA_LOG";
CREATE POLICY bi_ia_log_select ON public."BI_IA_LOG" FOR SELECT TO authenticated
  USING (user_id = auth.uid());
DROP POLICY IF EXISTS bi_ia_log_insert ON public."BI_IA_LOG";
CREATE POLICY bi_ia_log_insert ON public."BI_IA_LOG" FOR INSERT TO authenticated
  WITH CHECK (user_id = auth.uid());

-- ── 4) O SQL é seguro? ───────────────────────────────────────────────────
-- Uma instrução, só leitura, sem esquemas de sistema nem tabelas da lista
-- bloqueada. Devolve NULL quando pode rodar, ou o motivo quando não pode.
CREATE OR REPLACE FUNCTION public.bi_sql_seguro(p_sql text)
RETURNS text
LANGUAGE plpgsql
IMMUTABLE
SET search_path = public, pg_temp
AS $fn$
DECLARE
  s text := btrim(coalesce(p_sql, ''));
  sem_comentario text;
BEGIN
  IF s = '' THEN RETURN 'SQL vazio.'; END IF;
  -- tira comentários pra ninguém esconder nada atrás de -- ou /* */
  sem_comentario := regexp_replace(s, '--[^\n]*', '', 'g');
  sem_comentario := regexp_replace(sem_comentario, '/\*.*?\*/', '', 'gs');
  sem_comentario := btrim(sem_comentario);
  IF sem_comentario !~* '^(select|with)\s' THEN
    RETURN 'Só SELECT (ou WITH ... SELECT) pode rodar aqui.';
  END IF;
  -- ; no meio = segunda instrução; ; no fim é tolerado
  IF regexp_replace(sem_comentario, ';\s*$', '') ~ ';' THEN
    RETURN 'Uma instrução por vez — tire o ";" do meio.';
  END IF;
  IF sem_comentario ~* '\m(insert|update|delete|truncate|drop|alter|create|grant|revoke|copy|vacuum|analyze|refresh|call|execute|listen|notify|reset|lock|comment|security|cluster|reindex)\M' THEN
    RETURN 'Comando não permitido no BI (só leitura).';
  END IF;
  IF sem_comentario ~* '\m(pg_sleep|pg_read_file|pg_ls_dir|dblink|lo_import|lo_export|pg_terminate_backend|pg_cancel_backend|set_config|current_setting)\M' THEN
    RETURN 'Função não permitida no BI.';
  END IF;
  IF sem_comentario ~* '\m(auth|storage|vault|pg_catalog|information_schema|net|supabase_functions|extensions|realtime|graphql)\s*\.' THEN
    RETURN 'Esquema de sistema não pode ser consultado no BI.';
  END IF;
  IF sem_comentario ~* '\mpg_[a-z_]+' THEN
    RETURN 'Catálogo do Postgres não pode ser consultado no BI.';
  END IF;
  -- tabelas que não entram em BI: segredo, credencial, canal de ética, permissão
  IF sem_comentario ~* '(WA_BOT_CONFIG|DENUNCIA|COMITE_ETICA|CANAL_ETICA|senha|token|secret|credencial|screen_permission|access_audit|perfil_acesso|app_menu_acao|profiles)' THEN
    RETURN 'Essa tabela não pode entrar em BI (dado sensível).';
  END IF;
  RETURN NULL;
END $fn$;

-- ── 5) Substitui {{chave}} pelos filtros, sempre com quote_literal ───────
CREATE OR REPLACE FUNCTION public.bi_aplicar_params(p_sql text, p_params jsonb)
RETURNS text
LANGUAGE plpgsql
IMMUTABLE
SET search_path = public, pg_temp
AS $fn$
DECLARE
  s text := p_sql;
  k text;
  v text;
BEGIN
  FOR k IN SELECT m[1] FROM regexp_matches(p_sql, '\{\{\s*([a-zA-Z_][a-zA-Z0-9_]*)\s*\}\}', 'g') AS m LOOP
    v := CASE WHEN p_params IS NULL THEN NULL
              WHEN jsonb_typeof(p_params -> k) = 'null' THEN NULL
              ELSE p_params ->> k END;
    s := regexp_replace(s, '\{\{\s*' || k || '\s*\}\}',
                        CASE WHEN v IS NULL OR v = '' THEN 'NULL' ELSE quote_literal(v) END, 'g');
  END LOOP;
  RETURN s;
END $fn$;

-- ── 6) Executa (o miolo, compartilhado) ──────────────────────────────────
-- Devolve {colunas: [{nome, tipo}], linhas: [...], total, truncado, ms}.
CREATE OR REPLACE FUNCTION public.bi_rodar(p_sql text, p_params jsonb, p_limite int DEFAULT 5000)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $fn$
DECLARE
  motivo   text;
  sql_fin  text;
  linhas   jsonb;
  colunas  jsonb;
  t0       timestamptz := clock_timestamp();
  total    int;
BEGIN
  motivo := public.bi_sql_seguro(p_sql);
  IF motivo IS NOT NULL THEN
    RAISE EXCEPTION '%', motivo USING ERRCODE = '42501';
  END IF;
  sql_fin := regexp_replace(public.bi_aplicar_params(p_sql, p_params), ';\s*$', '');

  -- Só leitura e com prazo: um SELECT pesado não pode segurar o banco.
  PERFORM set_config('transaction_read_only', 'on', true);
  PERFORM set_config('statement_timeout', '20000', true);

  -- Duas camadas: a de dentro é o SQL do analista (pode ter ORDER BY/LIMIT
  -- próprios), a de fora impõe o teto.
  EXECUTE format('SELECT coalesce(jsonb_agg(to_jsonb(q)), ''[]''::jsonb) FROM (SELECT * FROM (%s) s LIMIT %s) q',
                 sql_fin, p_limite + 1)
     INTO linhas;

  total := jsonb_array_length(linhas);
  -- Tipos das colunas: pela primeira linha (json não guarda tipo numérico vs texto
  -- de forma confiável, mas o suficiente pra tela sugerir eixo/série).
  SELECT coalesce(jsonb_agg(jsonb_build_object('nome', k, 'tipo', jsonb_typeof(v))), '[]'::jsonb)
    INTO colunas
    FROM jsonb_each(coalesce(linhas -> 0, '{}'::jsonb)) AS e(k, v);

  RETURN jsonb_build_object(
    'colunas',  colunas,
    'linhas',   CASE WHEN total > p_limite
                     THEN (SELECT jsonb_agg(e.x) FROM (SELECT x FROM jsonb_array_elements(linhas) AS a(x) LIMIT p_limite) e)
                     ELSE linhas END,
    'total',    LEAST(total, p_limite),
    'truncado', total > p_limite,
    'ms',       (extract(epoch FROM clock_timestamp() - t0) * 1000)::int
  );
END $fn$;
REVOKE ALL ON FUNCTION public.bi_rodar(text, jsonb, int) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.bi_rodar(text, jsonb, int) FROM anon;
REVOKE ALL ON FUNCTION public.bi_rodar(text, jsonb, int) FROM authenticated;  -- só pelas duas abaixo

-- SQL livre: o analista, no editor.
CREATE OR REPLACE FUNCTION public.bi_executar_sql(p_sql text, p_params jsonb DEFAULT '{}'::jsonb, p_limite int DEFAULT 500)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $fn$
BEGIN
  IF NOT public.has_screen_access(auth.uid(), 'bi_estudio', 'alterar'::app_acao) THEN
    RAISE EXCEPTION 'Sem permissão para executar SQL no Estúdio de BI.' USING ERRCODE = '42501';
  END IF;
  RETURN public.bi_rodar(p_sql, p_params, LEAST(GREATEST(p_limite, 1), 5000));
END $fn$;
REVOKE ALL ON FUNCTION public.bi_executar_sql(text, jsonb, int) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.bi_executar_sql(text, jsonb, int) FROM anon;
GRANT EXECUTE ON FUNCTION public.bi_executar_sql(text, jsonb, int) TO authenticated;

-- O SQL gravado no widget: quem vê o painel.
CREATE OR REPLACE FUNCTION public.bi_widget_dados(p_widget_id bigint, p_params jsonb DEFAULT '{}'::jsonb)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $fn$
DECLARE
  w record;
BEGIN
  SELECT w1.sql, p.id AS painel_id, p.dono_id, p.publico INTO w
    FROM public."BI_WIDGET" w1 JOIN public."BI_PAINEL" p ON p.id = w1.painel_id
   WHERE w1.id = p_widget_id;
  IF w.sql IS NULL THEN
    RAISE EXCEPTION 'Gráfico #% não existe.', p_widget_id;
  END IF;
  IF NOT (w.dono_id = auth.uid()
          OR (w.publico AND public.has_screen_access(auth.uid(), 'bi_estudio', 'visualizar'::app_acao))) THEN
    RAISE EXCEPTION 'Sem permissão para ver este painel.' USING ERRCODE = '42501';
  END IF;
  RETURN public.bi_rodar(w.sql, p_params, 5000);
END $fn$;
REVOKE ALL ON FUNCTION public.bi_widget_dados(bigint, jsonb) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.bi_widget_dados(bigint, jsonb) FROM anon;
GRANT EXECUTE ON FUNCTION public.bi_widget_dados(bigint, jsonb) TO authenticated;

-- ── 7) Catálogo: o que existe pra consultar (pra tela e pra IA) ──────────
-- Tabelas e views do public, menos as bloqueadas, com colunas e tipos. É o
-- que a IA recebe pra escrever SQL certo — sem isso ela inventa coluna.
CREATE OR REPLACE FUNCTION public.bi_catalogo()
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $fn$
  SELECT CASE
    WHEN NOT public.has_screen_access(auth.uid(), 'bi_estudio', 'visualizar'::app_acao) THEN '[]'::jsonb
    ELSE coalesce((
      SELECT jsonb_agg(jsonb_build_object(
               'nome', t.table_name,
               'tipo', CASE WHEN t.table_type = 'VIEW' THEN 'view' ELSE 'tabela' END,
               'colunas', (SELECT jsonb_agg(jsonb_build_object('nome', c.column_name, 'tipo', c.data_type) ORDER BY c.ordinal_position)
                             FROM information_schema.columns c
                            WHERE c.table_schema = 'public' AND c.table_name = t.table_name)
             ) ORDER BY t.table_name)
        FROM information_schema.tables t
       WHERE t.table_schema = 'public'
         AND t.table_type IN ('BASE TABLE', 'VIEW')
         AND public.bi_sql_seguro('select 1 from "' || t.table_name || '"') IS NULL
         AND t.table_name NOT LIKE 'pg\_%'
         AND t.table_name NOT IN ('BI_IA_LOG')
    ), '[]'::jsonb)
  END;
$fn$;
REVOKE ALL ON FUNCTION public.bi_catalogo() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.bi_catalogo() FROM anon;
GRANT EXECUTE ON FUNCTION public.bi_catalogo() TO authenticated;

NOTIFY pgrst, 'reload schema';

-- =========================================================================
-- ROLLBACK
-- =========================================================================
-- DROP FUNCTION IF EXISTS public.bi_catalogo();
-- DROP FUNCTION IF EXISTS public.bi_widget_dados(bigint, jsonb);
-- DROP FUNCTION IF EXISTS public.bi_executar_sql(text, jsonb, int);
-- DROP FUNCTION IF EXISTS public.bi_rodar(text, jsonb, int);
-- DROP FUNCTION IF EXISTS public.bi_aplicar_params(text, jsonb);
-- DROP FUNCTION IF EXISTS public.bi_sql_seguro(text);
-- DROP FUNCTION IF EXISTS public.bi_set_atualizado_em();
-- DROP TABLE IF EXISTS public."BI_IA_LOG";
-- DROP TABLE IF EXISTS public."BI_WIDGET";
-- DROP TABLE IF EXISTS public."BI_PAINEL";
-- DELETE FROM public.app_menu_acao WHERE menu_codigo = 'bi_estudio';
-- DELETE FROM public.app_menu WHERE codigo = 'bi_estudio';
-- NOTIFY pgrst, 'reload schema';
