-- =====================================================================
-- CENTRAL DE SERVIÇOS — AGENDAMENTO DE VEÍCULOS
--
-- Reserva da frota pelo colaborador: escolhe o veículo, a data e o turno,
-- diz a quais contratos a viagem atende e confirma. O quadro de quem está
-- com o carro em cada dia passa a existir num lugar só.
--
-- DECISÕES QUE VALEM A LEITURA
--
--   1. A FROTA NÃO É NOSSA. Os veículos já vivem em `sup_patrimonio`
--      (categoria = 'veiculo'), cadastrados pelo módulo de Patrimônio. Este
--      módulo NÃO cria, NÃO altera e NÃO apaga nada lá — só lê. Quem diz se
--      o carro está na oficina continua sendo o Patrimônio, pelas colunas
--      `em_manutencao`, `data_inicio_manutencao` e `data_previsao_fim`.
--
--   2. SEM FK PARA sup_patrimonio. `patrimonio_id` é um uuid solto de
--      propósito. Uma FK daqui criaria uma dependência que passaria a
--      recusar DELETE do outro lado — ou seja, este módulo mudaria o
--      comportamento do Patrimônio sem ter tocado numa linha dele. O nome e
--      a placa ficam desnormalizados na reserva, então o histórico continua
--      legível mesmo se o bem for descadastrado depois.
--
--   3. A LEITURA DA FROTA É RPC, NÃO SELECT DIRETO. A policy de SELECT de
--      sup_patrimonio exige can_access('sup_patrimonio'|'sup_manutencao'),
--      que o colaborador comum não tem — e afrouxá-la seria alterar o módulo
--      de Patrimônio. `cs_veiculos_frota()` é SECURITY DEFINER e devolve
--      apenas os campos da frota que a tela precisa, para quem tem o menu
--      desta tela. Nenhuma policy de lá foi tocada.
--
--   4. INDISPONIBILIDADE É REGRA DE BANCO, NÃO DE TELA. O card cinza é
--      cortesia; quem recusa a reserva é o trigger. Dois caminhos levam ao
--      mesmo "não pode": manutenção e choque com outra reserva.
--
-- ROLLBACK:
--   DROP TABLE IF EXISTS public.cs_veiculo_agendamento_log,
--     public.cs_veiculo_agendamento_contrato, public.cs_veiculo_agendamento CASCADE;
--   DROP FUNCTION IF EXISTS public.cs_veiculos_frota(),
--     public.cs_veiculo_motivo_indisponivel(uuid, date, date),
--     public.cs_veic_checar_agendamento(), public.cs_veic_registrar_log();
--   DELETE FROM public.app_menu WHERE codigo LIKE 'central_servicos_veiculos%';
-- =====================================================================

-- ── 1. Menus ─────────────────────────────────────────────────────────
-- O módulo "central_servicos" já existe (20260625000003_modulo_central_servicos).
INSERT INTO public.app_menu (modulo_id, codigo, nome, rota, ordem)
SELECT m.id, x.codigo, x.nome, x.rota, x.ordem
  FROM (VALUES
    ('central_servicos_veiculos',          'Agendamento de Veículos',      '/app/central-servicos/veiculos', 40),
    -- Quem cuida da frota: enxerga e cancela reserva de qualquer pessoa.
    ('central_servicos_veiculos_gestor',   'Veículos — Gestão da Frota',   NULL,                             41)
  ) AS x(codigo, nome, rota, ordem)
  JOIN public.app_modulo m ON m.codigo = 'central_servicos'
ON CONFLICT (modulo_id, codigo) DO NOTHING;

-- ── 2. A reserva ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.cs_veiculo_agendamento (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  -- Número de protocolo, o que o usuário fala no telefone ("o agendamento 42").
  numero        bigint GENERATED BY DEFAULT AS IDENTITY,
  empresa_id    uuid NOT NULL REFERENCES public.empresas(id) ON DELETE CASCADE,

  -- Ver decisão 2: sem FK, e com o nome/placa congelados na reserva.
  patrimonio_id         uuid NOT NULL,
  veiculo_nome          text NOT NULL,
  veiculo_identificador text,

  data_inicio   date NOT NULL,
  data_fim      date NOT NULL,
  -- 'dia_todo' é o padrão porque é como a frota realmente é usada; os meios
  -- turnos existem para o caso de dois destinos próximos no mesmo dia.
  turno         text NOT NULL DEFAULT 'dia_todo'
                CHECK (turno IN ('manha', 'tarde', 'dia_todo')),

  destino       text,
  motivo        text,
  observacoes   text,

  status        text NOT NULL DEFAULT 'confirmado'
                CHECK (status IN ('confirmado', 'cancelado', 'concluido')),
  motivo_cancelamento text,

  solicitante_id    uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  solicitante_nome  text,

  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT cs_veic_periodo_coerente CHECK (data_fim >= data_inicio),
  -- Cancelamento sem motivo vira mistério três meses depois.
  CONSTRAINT cs_veic_cancelamento_com_motivo CHECK (
    status <> 'cancelado' OR btrim(coalesce(motivo_cancelamento, '')) <> ''
  )
);

CREATE INDEX IF NOT EXISTS idx_cs_veic_agend_veiculo
  ON public.cs_veiculo_agendamento(patrimonio_id, data_inicio, data_fim);
CREATE INDEX IF NOT EXISTS idx_cs_veic_agend_solicitante
  ON public.cs_veiculo_agendamento(solicitante_id, data_inicio DESC);
CREATE INDEX IF NOT EXISTS idx_cs_veic_agend_periodo
  ON public.cs_veiculo_agendamento(data_inicio, data_fim) WHERE status = 'confirmado';

DROP TRIGGER IF EXISTS trg_cs_veic_agend_updated ON public.cs_veiculo_agendamento;
CREATE TRIGGER trg_cs_veic_agend_updated BEFORE UPDATE ON public.cs_veiculo_agendamento
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ── 3. Contratos atendidos pela viagem ───────────────────────────────
-- Tabela filha e não array: a mesma viagem costuma atender vários contratos
-- (é o caso dos prints — "UFFS PASSO FUNDO, UFFS ERECHIM…"), e assim dá para
-- responder "quanto a frota rodou para o contrato X" com um GROUP BY.
CREATE TABLE IF NOT EXISTS public.cs_veiculo_agendamento_contrato (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  agendamento_id uuid NOT NULL REFERENCES public.cs_veiculo_agendamento(id) ON DELETE CASCADE,
  -- SET NULL, nunca RESTRICT: apagar um contrato é assunto do módulo de
  -- Contratos e não pode esbarrar no histórico de carona da frota.
  contrato_id    uuid REFERENCES public.contratos(id) ON DELETE SET NULL,
  contrato_nome  text NOT NULL,
  UNIQUE (agendamento_id, contrato_id)
);
CREATE INDEX IF NOT EXISTS idx_cs_veic_agend_contrato
  ON public.cs_veiculo_agendamento_contrato(agendamento_id);

-- ── 4. Auditoria ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.cs_veiculo_agendamento_log (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  agendamento_id uuid,
  acao           text NOT NULL,
  detalhe        text,
  usuario_id     uuid,
  usuario_nome   text,
  created_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_cs_veic_log
  ON public.cs_veiculo_agendamento_log(agendamento_id, created_at DESC);

-- ── 5. Frota (leitura de sup_patrimonio) ─────────────────────────────
-- Ver decisão 3. Só lê; devolve o recorte que a tela mostra e nada além.
CREATE OR REPLACE FUNCTION public.cs_veiculos_frota()
RETURNS TABLE (
  id                     uuid,
  nome                   text,
  identificador          text,
  lotacao                text,
  contrato_nome          text,
  em_manutencao          boolean,
  data_inicio_manutencao date,
  data_previsao_fim      date
)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public, pg_temp
AS $$
  SELECT p.id, p.nome, p.identificador, p.lotacao, c.nome,
         p.em_manutencao, p.data_inicio_manutencao, p.data_previsao_fim
    FROM public.sup_patrimonio p
    LEFT JOIN public.contratos c ON c.id = p.contrato_id
   WHERE p.categoria = 'veiculo'
     AND p.ativo
     AND public.tem_acesso_menu('central_servicos_veiculos')
     -- SECURITY DEFINER vê tudo; o escopo de empresa precisa vir explícito.
     AND p.empresa_id IN (
       SELECT ue.empresa_id FROM public.user_empresa ue WHERE ue.user_id = auth.uid()
     )
   ORDER BY p.nome;
$$;
REVOKE ALL ON FUNCTION public.cs_veiculos_frota() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.cs_veiculos_frota() TO authenticated;

-- ── 6. O veículo pode rodar neste período? ───────────────────────────
-- Devolve o motivo do "não" em texto, ou NULL quando está liberado. Uma
-- função só, usada pelo trigger e pela tela — assim a mensagem que o usuário
-- lê é literalmente a mesma que o banco usaria para recusar.
--
-- A leitura das três colunas do Patrimônio:
--   em_manutencao = false ......... livre.
--   true  + previsão de fim ....... bloqueado até a previsão; depois dela,
--                                   agendar é permitido (a oficina já tem
--                                   data para devolver o carro).
--   true  sem previsão de fim ..... bloqueado sem prazo — é o
--                                   "retorno por tempo indeterminado".
CREATE OR REPLACE FUNCTION public.cs_veiculo_motivo_indisponivel(
  p_patrimonio_id uuid,
  p_data_inicio   date,
  p_data_fim      date
)
RETURNS text
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public, pg_temp
AS $$
DECLARE
  v  record;
  vc record;
BEGIN
  SELECT nome, ativo, em_manutencao, data_inicio_manutencao, data_previsao_fim
    INTO v
    FROM public.sup_patrimonio
   WHERE id = p_patrimonio_id AND categoria = 'veiculo';

  IF NOT FOUND THEN
    RETURN 'Veículo não encontrado no cadastro de Patrimônio.';
  END IF;
  IF NOT v.ativo THEN
    RETURN 'Veículo inativo no cadastro de Patrimônio.';
  END IF;

  IF v.em_manutencao THEN
    IF v.data_previsao_fim IS NULL THEN
      RETURN 'Veículo em manutenção — retorno por tempo indeterminado.';
    ELSIF p_data_inicio <= v.data_previsao_fim THEN
      RETURN 'Veículo em manutenção até ' || to_char(v.data_previsao_fim, 'DD/MM/YYYY')
             || '. Agende a partir de ' || to_char(v.data_previsao_fim + 1, 'DD/MM/YYYY') || '.';
    END IF;
  END IF;

  -- Choque com outra reserva. Períodos se cruzam quando cada um começa antes
  -- de o outro terminar; o turno só livra quando os dois são meio período e
  -- períodos diferentes.
  SELECT a.numero, a.solicitante_nome, a.data_inicio, a.data_fim, a.turno
    INTO vc
    FROM public.cs_veiculo_agendamento a
   WHERE a.patrimonio_id = p_patrimonio_id
     AND a.status = 'confirmado'
     AND a.data_inicio <= p_data_fim
     AND a.data_fim    >= p_data_inicio
   ORDER BY a.data_inicio
   LIMIT 1;

  IF FOUND THEN
    RETURN 'Já existe a reserva nº ' || vc.numero || ' de '
           || coalesce(vc.solicitante_nome, 'outro colaborador') || ' para '
           || to_char(vc.data_inicio, 'DD/MM/YYYY')
           || CASE WHEN vc.data_fim <> vc.data_inicio
                   THEN ' a ' || to_char(vc.data_fim, 'DD/MM/YYYY') ELSE '' END || '.';
  END IF;

  RETURN NULL;
END $$;
REVOKE ALL ON FUNCTION public.cs_veiculo_motivo_indisponivel(uuid, date, date) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.cs_veiculo_motivo_indisponivel(uuid, date, date) TO authenticated;

-- ── 7. Trigger de validação ──────────────────────────────────────────
-- A checagem de conflito da função acima ignora o turno de propósito (ela
-- serve também para a tela pintar o card). Aqui o turno entra: dois meios
-- turnos diferentes cabem no mesmo dia.
CREATE OR REPLACE FUNCTION public.cs_veic_checar_agendamento()
RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp
AS $$
DECLARE
  v_manut record;
  v_conf  record;
BEGIN
  IF NEW.status <> 'confirmado' THEN
    RETURN NEW;  -- cancelado/concluído não disputa o carro com ninguém
  END IF;

  -- Só na criação (ou quando a data muda): senão o gestor não conseguiria
  -- corrigir o destino de uma viagem que já começou.
  IF (TG_OP = 'INSERT' OR NEW.data_inicio IS DISTINCT FROM OLD.data_inicio)
     AND NEW.data_inicio < CURRENT_DATE THEN
    RAISE EXCEPTION 'Não dá para agendar um veículo para uma data que já passou.';
  END IF;

  SELECT ativo, em_manutencao, data_previsao_fim INTO v_manut
    FROM public.sup_patrimonio
   WHERE id = NEW.patrimonio_id AND categoria = 'veiculo';

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Veículo não encontrado no cadastro de Patrimônio.';
  END IF;
  IF NOT v_manut.ativo THEN
    RAISE EXCEPTION 'Veículo inativo no cadastro de Patrimônio.';
  END IF;
  IF v_manut.em_manutencao
     AND (v_manut.data_previsao_fim IS NULL OR NEW.data_inicio <= v_manut.data_previsao_fim) THEN
    RAISE EXCEPTION 'Veículo em manutenção: %',
      coalesce('previsão de retorno em ' || to_char(v_manut.data_previsao_fim, 'DD/MM/YYYY'),
               'retorno por tempo indeterminado');
  END IF;

  SELECT a.numero, a.data_inicio, a.data_fim INTO v_conf
    FROM public.cs_veiculo_agendamento a
   WHERE a.patrimonio_id = NEW.patrimonio_id
     AND a.id <> NEW.id
     AND a.status = 'confirmado'
     AND a.data_inicio <= NEW.data_fim
     AND a.data_fim    >= NEW.data_inicio
     AND (a.turno = 'dia_todo' OR NEW.turno = 'dia_todo' OR a.turno = NEW.turno)
   LIMIT 1;

  IF FOUND THEN
    RAISE EXCEPTION 'Veículo já reservado nesse período (reserva nº %, de % a %).',
      v_conf.numero, to_char(v_conf.data_inicio, 'DD/MM/YYYY'), to_char(v_conf.data_fim, 'DD/MM/YYYY');
  END IF;

  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS trg_cs_veic_checar ON public.cs_veiculo_agendamento;
CREATE TRIGGER trg_cs_veic_checar
  BEFORE INSERT OR UPDATE ON public.cs_veiculo_agendamento
  FOR EACH ROW EXECUTE FUNCTION public.cs_veic_checar_agendamento();

-- Nome do solicitante congelado no ato — o display_name pode mudar depois.
CREATE OR REPLACE FUNCTION public.cs_veic_preencher_solicitante()
RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp
AS $$
BEGIN
  IF btrim(coalesce(NEW.solicitante_nome, '')) = '' THEN
    NEW.solicitante_nome := (SELECT display_name FROM public.profiles WHERE id = NEW.solicitante_id);
  END IF;
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS trg_cs_veic_solicitante ON public.cs_veiculo_agendamento;
CREATE TRIGGER trg_cs_veic_solicitante
  BEFORE INSERT ON public.cs_veiculo_agendamento
  FOR EACH ROW EXECUTE FUNCTION public.cs_veic_preencher_solicitante();

-- Auditoria que nunca derruba a operação (mesmo contrato do trigger de log
-- do Patrimônio: se a auditoria falhar, a reserva ainda vale).
CREATE OR REPLACE FUNCTION public.cs_veic_registrar_log()
RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp
AS $$
DECLARE
  v_nome text := coalesce((SELECT display_name FROM public.profiles WHERE id = auth.uid()), 'sistema');
BEGIN
  BEGIN
    IF TG_OP = 'INSERT' THEN
      INSERT INTO public.cs_veiculo_agendamento_log (agendamento_id, acao, detalhe, usuario_id, usuario_nome)
      VALUES (NEW.id, 'criado',
              NEW.veiculo_nome || ' — ' || to_char(NEW.data_inicio, 'DD/MM/YYYY'),
              auth.uid(), v_nome);
    ELSIF TG_OP = 'UPDATE' AND NEW.status IS DISTINCT FROM OLD.status THEN
      INSERT INTO public.cs_veiculo_agendamento_log (agendamento_id, acao, detalhe, usuario_id, usuario_nome)
      VALUES (NEW.id, NEW.status,
              coalesce(NEW.motivo_cancelamento, OLD.status || ' → ' || NEW.status),
              auth.uid(), v_nome);
    ELSIF TG_OP = 'DELETE' THEN
      INSERT INTO public.cs_veiculo_agendamento_log (agendamento_id, acao, detalhe, usuario_id, usuario_nome)
      VALUES (OLD.id, 'excluido', OLD.veiculo_nome, auth.uid(), v_nome);
    END IF;
  EXCEPTION WHEN others THEN
    NULL;
  END;
  RETURN COALESCE(NEW, OLD);
END $$;

DROP TRIGGER IF EXISTS trg_cs_veic_log ON public.cs_veiculo_agendamento;
CREATE TRIGGER trg_cs_veic_log
  AFTER INSERT OR UPDATE OR DELETE ON public.cs_veiculo_agendamento
  FOR EACH ROW EXECUTE FUNCTION public.cs_veic_registrar_log();

-- ── 8. RLS ───────────────────────────────────────────────────────────
-- A agenda da frota é pública para quem tem a tela: o "Calendário Geral"
-- existe justamente para todo mundo enxergar quem está com o carro. O que é
-- restrito é MEXER — cada um cuida da própria reserva, e o gestor da frota
-- cuida de todas.
ALTER TABLE public.cs_veiculo_agendamento           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cs_veiculo_agendamento_contrato  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cs_veiculo_agendamento_log       ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS cs_veic_agend_select ON public.cs_veiculo_agendamento;
CREATE POLICY cs_veic_agend_select ON public.cs_veiculo_agendamento
  FOR SELECT TO authenticated
  USING (
    public.tem_acesso_menu('central_servicos_veiculos')
    AND empresa_id IN (
      SELECT ue.empresa_id FROM public.user_empresa ue WHERE ue.user_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS cs_veic_agend_insert ON public.cs_veiculo_agendamento;
CREATE POLICY cs_veic_agend_insert ON public.cs_veiculo_agendamento
  FOR INSERT TO authenticated
  WITH CHECK (
    public.tem_acesso_menu('central_servicos_veiculos', 'incluir')
    AND solicitante_id = auth.uid()   -- ninguém reserva em nome de outro
    AND status = 'confirmado'
    AND empresa_id IN (
      SELECT ue.empresa_id FROM public.user_empresa ue WHERE ue.user_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS cs_veic_agend_update ON public.cs_veiculo_agendamento;
CREATE POLICY cs_veic_agend_update ON public.cs_veiculo_agendamento
  FOR UPDATE TO authenticated
  USING (
    (solicitante_id = auth.uid() OR public.tem_acesso_menu('central_servicos_veiculos_gestor'))
    AND public.tem_acesso_menu('central_servicos_veiculos')
  )
  WITH CHECK (
    (solicitante_id = auth.uid() OR public.tem_acesso_menu('central_servicos_veiculos_gestor'))
    AND public.tem_acesso_menu('central_servicos_veiculos')
  );

-- Excluir de vez é do gestor da frota; o colaborador cancela (com motivo),
-- e o cancelamento fica no histórico.
DROP POLICY IF EXISTS cs_veic_agend_delete ON public.cs_veiculo_agendamento;
CREATE POLICY cs_veic_agend_delete ON public.cs_veiculo_agendamento
  FOR DELETE TO authenticated
  USING (public.tem_acesso_menu('central_servicos_veiculos_gestor'));

-- Os contratos herdam a visibilidade e a permissão de escrita da reserva.
DROP POLICY IF EXISTS cs_veic_contrato_select ON public.cs_veiculo_agendamento_contrato;
CREATE POLICY cs_veic_contrato_select ON public.cs_veiculo_agendamento_contrato
  FOR SELECT TO authenticated
  USING (EXISTS (
    SELECT 1 FROM public.cs_veiculo_agendamento a WHERE a.id = agendamento_id
  ));

DROP POLICY IF EXISTS cs_veic_contrato_write ON public.cs_veiculo_agendamento_contrato;
CREATE POLICY cs_veic_contrato_write ON public.cs_veiculo_agendamento_contrato
  FOR ALL TO authenticated
  USING (EXISTS (
    SELECT 1 FROM public.cs_veiculo_agendamento a
     WHERE a.id = agendamento_id
       AND (a.solicitante_id = auth.uid() OR public.tem_acesso_menu('central_servicos_veiculos_gestor'))
  ))
  WITH CHECK (EXISTS (
    SELECT 1 FROM public.cs_veiculo_agendamento a
     WHERE a.id = agendamento_id
       AND (a.solicitante_id = auth.uid() OR public.tem_acesso_menu('central_servicos_veiculos_gestor'))
  ));

DROP POLICY IF EXISTS cs_veic_log_select ON public.cs_veiculo_agendamento_log;
CREATE POLICY cs_veic_log_select ON public.cs_veiculo_agendamento_log
  FOR SELECT TO authenticated
  USING (public.tem_acesso_menu('central_servicos_veiculos'));
-- Escrita só pelo trigger (SECURITY DEFINER): ninguém forja linha de log.

-- ── 9. Permissão inicial ─────────────────────────────────────────────
-- tem_acesso_menu() nega por padrão: sem nenhuma linha aqui, NINGUÉM
-- conseguiria nem abrir a tela — nem quem administra o sistema. Semear os
-- perfis "concede_tudo" é o que torna o módulo utilizável no minuto seguinte
-- ao deploy; o acesso dos demais continua saindo de Administração › Acesso
-- por Usuário, que segue sendo a única autoridade.
INSERT INTO public.perfil_acesso_permissao (perfil_id, menu_codigo, acao, allow)
SELECT pa.id, m.codigo, a.acao, true
  FROM public.perfil_acesso pa
 CROSS JOIN (VALUES ('central_servicos_veiculos'), ('central_servicos_veiculos_gestor')) AS m(codigo)
 CROSS JOIN (VALUES ('visualizar'::public.app_acao), ('incluir'::public.app_acao),
                    ('alterar'::public.app_acao), ('excluir'::public.app_acao)) AS a(acao)
 WHERE pa.concede_tudo AND pa.ativo
ON CONFLICT (perfil_id, menu_codigo, acao) DO NOTHING;

-- ── 10. Conferência ──────────────────────────────────────────────────
SELECT am.codigo, am.nome, am.rota
  FROM public.app_menu am
 WHERE am.codigo LIKE 'central_servicos_veiculos%';

NOTIFY pgrst, 'reload schema';
