-- =========================================================================
-- Férias: histórico de quem fez o quê (criou, aprovou, reprovou, cancelou)
--
-- Pedido do Pablo em 15/09/2026: "nas solicitações de férias tem 'Aprovada'
-- mas não tem quem aprovou — tem que ter um histórico".
--
-- A tabela já guardava aprovado_por/aprovado_em, mas só o ÚLTIMO carimbo,
-- sobrescrito a cada mudança. Aqui nasce a linha do tempo:
--   SISTEMA_SOLICITACOES_FERIAS_HISTORICO — uma linha por evento (criada,
--   e cada troca de status), com quem, quando e o motivo (reprovação).
--   Escrita SÓ pelo trigger (SECURITY DEFINER); a tela lê.
--
-- Estoque: as 18 solicitações existentes ganham "Criada" (solicitante +
-- criado_em) e, quando não estão Pendente, o evento do status atual com
-- aprovado_por/aprovado_em — é tudo o que se sabe do passado.
--
-- Idempotente. Aplicar no banco do app.
-- =========================================================================

CREATE TABLE IF NOT EXISTS public."SISTEMA_SOLICITACOES_FERIAS_HISTORICO" (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  solicitacao_id bigint NOT NULL REFERENCES public."SISTEMA_SOLICITACOES_FERIAS"(id) ON DELETE CASCADE,
  evento         text NOT NULL,          -- 'Criada' | 'Aprovada' | 'Reprovada' | 'Cancelada' | 'Pendente' (reaberta)
  de_status      text,
  para_status    text,
  por_nome       text,
  por_user_id    uuid,
  motivo         text,
  criado_em      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_ferias_hist_solicitacao ON public."SISTEMA_SOLICITACOES_FERIAS_HISTORICO"(solicitacao_id, criado_em);

ALTER TABLE public."SISTEMA_SOLICITACOES_FERIAS_HISTORICO" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON public."SISTEMA_SOLICITACOES_FERIAS_HISTORICO" TO authenticated;
DROP POLICY IF EXISTS ferias_hist_select ON public."SISTEMA_SOLICITACOES_FERIAS_HISTORICO";
CREATE POLICY ferias_hist_select ON public."SISTEMA_SOLICITACOES_FERIAS_HISTORICO" FOR SELECT TO authenticated
  USING (true);   -- a própria SISTEMA_SOLICITACOES_FERIAS é aberta a authenticated (sf_all_auth)

-- ── Trigger: grava o evento a cada INSERT e a cada troca de status ────────
CREATE OR REPLACE FUNCTION public.ferias_registrar_historico()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $fn$
DECLARE
  v_nome text;
BEGIN
  IF TG_OP = 'INSERT' THEN
    INSERT INTO public."SISTEMA_SOLICITACOES_FERIAS_HISTORICO" (solicitacao_id, evento, de_status, para_status, por_nome, por_user_id)
    VALUES (NEW.id, 'Criada', NULL, NEW.status, NEW.solicitante_nome, auth.uid());
    RETURN NEW;
  END IF;
  IF NEW.status IS DISTINCT FROM OLD.status THEN
    -- Quem decidiu: a tela grava aprovado_por junto com o status; sem ele,
    -- cai no nome do usuário logado (profiles) e por fim no e-mail.
    v_nome := NULLIF(btrim(coalesce(NEW.aprovado_por, '')), '');
    IF v_nome IS NULL AND auth.uid() IS NOT NULL THEN
      SELECT coalesce(NULLIF(p.display_name, ''), p.email) INTO v_nome FROM public.profiles p WHERE p.id = auth.uid();
    END IF;
    INSERT INTO public."SISTEMA_SOLICITACOES_FERIAS_HISTORICO" (solicitacao_id, evento, de_status, para_status, por_nome, por_user_id, motivo)
    VALUES (NEW.id, NEW.status, OLD.status, NEW.status, v_nome, auth.uid(),
            CASE WHEN NEW.status = 'Reprovada' THEN NULLIF(btrim(coalesce(NEW.motivo_reprovacao, '')), '') END);
  END IF;
  RETURN NEW;
END $fn$;

DROP TRIGGER IF EXISTS trg_ferias_historico ON public."SISTEMA_SOLICITACOES_FERIAS";
CREATE TRIGGER trg_ferias_historico
  AFTER INSERT OR UPDATE OF status ON public."SISTEMA_SOLICITACOES_FERIAS"
  FOR EACH ROW EXECUTE FUNCTION public.ferias_registrar_historico();

-- ── Estoque: o que dá pra reconstruir do passado ─────────────────────────
INSERT INTO public."SISTEMA_SOLICITACOES_FERIAS_HISTORICO" (solicitacao_id, evento, de_status, para_status, por_nome, criado_em)
SELECT f.id, 'Criada', NULL, 'Pendente', f.solicitante_nome, coalesce(f.criado_em, now())
  FROM public."SISTEMA_SOLICITACOES_FERIAS" f
 WHERE NOT EXISTS (SELECT 1 FROM public."SISTEMA_SOLICITACOES_FERIAS_HISTORICO" h WHERE h.solicitacao_id = f.id AND h.evento = 'Criada');

INSERT INTO public."SISTEMA_SOLICITACOES_FERIAS_HISTORICO" (solicitacao_id, evento, de_status, para_status, por_nome, motivo, criado_em)
SELECT f.id, f.status, 'Pendente', f.status, f.aprovado_por,
       CASE WHEN f.status = 'Reprovada' THEN f.motivo_reprovacao END,
       coalesce(f.aprovado_em, f.atualizado_em, now())
  FROM public."SISTEMA_SOLICITACOES_FERIAS" f
 WHERE f.status <> 'Pendente'
   AND NOT EXISTS (SELECT 1 FROM public."SISTEMA_SOLICITACOES_FERIAS_HISTORICO" h WHERE h.solicitacao_id = f.id AND h.evento = f.status);

NOTIFY pgrst, 'reload schema';

-- Conferência
-- SELECT evento, count(*) FROM public."SISTEMA_SOLICITACOES_FERIAS_HISTORICO" GROUP BY 1;

-- =========================================================================
-- ROLLBACK
-- =========================================================================
-- DROP TRIGGER IF EXISTS trg_ferias_historico ON public."SISTEMA_SOLICITACOES_FERIAS";
-- DROP FUNCTION IF EXISTS public.ferias_registrar_historico();
-- DROP TABLE IF EXISTS public."SISTEMA_SOLICITACOES_FERIAS_HISTORICO";
-- NOTIFY pgrst, 'reload schema';
