-- SIS-2026-0305: seed do catálogo de tipos de documento com os 38 nomes
-- reais já cadastrados no legado (dados/financeiro.db, tabela sol_tipos,
-- ativo=1) — diferente do dado transacional (solicitações/itens/anexos),
-- que fica pra fase separada de migração histórica, este é só catálogo de
-- configuração (autocomplete), sem risco de conflito com uso ao vivo.
INSERT INTO public."SOLICITACAO_AJUSTE_TIPO" (nome) VALUES
  ('AJUSTE DE PONTO'),
  ('AVISO PRÉVIO'),
  ('CARTÕES PONTO ASSINADOS'),
  ('COMPROVANTE BSF'),
  ('COMPROVANTE DE FGTS'),
  ('COMPROVANTE DE FÉRIAS'),
  ('COMPROVANTE DE PRÊMIO ASSIDUIDADE'),
  ('COMPROVANTE DE RESCISÃO'),
  ('COMPROVANTE DE SALÁRIO'),
  ('COMPROVANTE DE SEGURO DE VIDA'),
  ('COMPROVANTE DE VA'),
  ('COMPROVANTE DE VT'),
  ('DCTFWEB'),
  ('DIFERENÇA DE CCT'),
  ('DOCUMENTOS'),
  ('DOCUMENTOS ADMISSIONAIS'),
  ('DOCUMENTOS COMPROBATÓRIOS'),
  ('DOCUMENTOS DE FÉRIAS ASSINADOS'),
  ('DOCUMENTOS RESCISÓRIOS'),
  ('DOCUMENTOS RESCISÓRIOS ASSINADOS'),
  ('DOCUMENTOS RESCISÓRIOS HOMOLOGADOS'),
  ('ESCLARECIMENTO QUANTO A DESCONTO'),
  ('ESCLARECIMENTO QUANTO A DESCONTO NO CONTRACHEQUE'),
  ('ESCLARECIMENTO QUANTO A DIFERENÇA DE VALORES INSS'),
  ('ESCLARECIMENTO QUANTO A INCONSISTENCIAS NO CARTÃO PONTO'),
  ('ESCLARECIMENTO QUANTO A VALORES DE ASSIDUIDADE'),
  ('ESCLARECIMENTO QUANTO A VALORES DE FGTS'),
  ('ESCLARECIMENTOS'),
  ('ESCLARECIMENTOS QUANTO A VALORES DE SALÁRIO'),
  ('ESCLARECIMENTOS QUANTO A VALORES DE VA'),
  ('ESCLARECIMENTOS QUANTO A VALORES DE VT'),
  ('EXTRATO PREVIDENCIÁRIO'),
  ('FICHA DE EPI/UNIFORME/CRACHÁ'),
  ('FOLHA DE PAGAMENTO'),
  ('GUIA DE FGTS'),
  ('MEMÓRIA DE CALCULO'),
  ('TERMO DE PRORROGAÇÃO'),
  ('TERMOS DE OPÇÃO DE VT')
ON CONFLICT (nome) DO NOTHING;

NOTIFY pgrst, 'reload schema';

-- =====================================================================
-- ROLLBACK
--   DELETE FROM public."SOLICITACAO_AJUSTE_TIPO" WHERE nome IN (
--     'AJUSTE DE PONTO','AVISO PRÉVIO','CARTÕES PONTO ASSINADOS','COMPROVANTE BSF',
--     'COMPROVANTE DE FGTS','COMPROVANTE DE FÉRIAS','COMPROVANTE DE PRÊMIO ASSIDUIDADE',
--     'COMPROVANTE DE RESCISÃO','COMPROVANTE DE SALÁRIO','COMPROVANTE DE SEGURO DE VIDA',
--     'COMPROVANTE DE VA','COMPROVANTE DE VT','DCTFWEB','DIFERENÇA DE CCT','DOCUMENTOS',
--     'DOCUMENTOS ADMISSIONAIS','DOCUMENTOS COMPROBATÓRIOS','DOCUMENTOS DE FÉRIAS ASSINADOS',
--     'DOCUMENTOS RESCISÓRIOS','DOCUMENTOS RESCISÓRIOS ASSINADOS','DOCUMENTOS RESCISÓRIOS HOMOLOGADOS',
--     'ESCLARECIMENTO QUANTO A DESCONTO','ESCLARECIMENTO QUANTO A DESCONTO NO CONTRACHEQUE',
--     'ESCLARECIMENTO QUANTO A DIFERENÇA DE VALORES INSS','ESCLARECIMENTO QUANTO A INCONSISTENCIAS NO CARTÃO PONTO',
--     'ESCLARECIMENTO QUANTO A VALORES DE ASSIDUIDADE','ESCLARECIMENTO QUANTO A VALORES DE FGTS',
--     'ESCLARECIMENTOS','ESCLARECIMENTOS QUANTO A VALORES DE SALÁRIO','ESCLARECIMENTOS QUANTO A VALORES DE VA',
--     'ESCLARECIMENTOS QUANTO A VALORES DE VT','EXTRATO PREVIDENCIÁRIO','FICHA DE EPI/UNIFORME/CRACHÁ',
--     'FOLHA DE PAGAMENTO','GUIA DE FGTS','MEMÓRIA DE CALCULO','TERMO DE PRORROGAÇÃO','TERMOS DE OPÇÃO DE VT'
--   );
-- =====================================================================
