-- =========================================================================
-- ENCARREGADOS › CONFERÊNCIA DE PONTO (07/10/2026)
--
-- PEDIDO (Pablo): "os encarregados precisam enviar seus pontos pro
-- operacional no começo da folha de pagamento. A etapa iniciava no
-- operacional antes, mas agora vai iniciar no encarregados. Deixa todos sem
-- permissão por enquanto, ainda vamos modificar bastante coisa."
--
-- O FLUXO (a Conferência de Ponto ganha uma casa ANTES do Operacional):
--
--   Encarregado monta o ENVIO do mês para o contrato (Empresa, Filial):
--     · a lista dos colaboradores do contrato, cada um com a situação do mês
--       (ok, faltas, atestado, férias, afastado, desligado, divergência),
--       faltas/atrasos/horas extras e observação — a tela já traz o que o
--       relógio (espelho."BiMarcacoes") registrou: dias com batida e dias
--       úteis sem batida, para ele conferir antes de mandar;
--     · os arquivos das folhas/espelhos de ponto (obrigatório ≥ 1).
--   Enviar → o envio fica "enviado" e a linha do contrato na Conferência de
--   Ponto (SISTEMA_CONFERENCIA_PONTO) passa de "Pendente Encarregados" para
--   "Pendente Operacional" (ou nasce assim).
--   O Operacional RECEBE (ok) ou DEVOLVE com motivo — o encarregado recebe a
--   notificação, corrige e reenvia.
--
-- STATUS NOVO "Pendente Encarregados": é o status de quem ainda não tem
-- envio. O Operacional CONTINUA podendo conferir/aprovar a partir dele —
-- enquanto ninguém tem a tela dos encarregados liberada, o fluxo de hoje
-- não pode travar.
--
-- PERMISSÕES — nenhuma concedida (pedido explícito). Menus criados:
--   encarregados_conferencia_ponto  (tela, módulo Encarregados)
--   ponto_receber_encarregados      (fantasma, Operacional: receber/devolver)
-- Liberar em Administração › Acesso por Usuário quando for a hora.
--
-- Idempotente. Aplicar no banco do app — não se auto-aplica. Depende da
-- 20261007000021 (diaria_ponto_sincronizado_ate) para o "relógio até".
-- =========================================================================

-- ── 1) Menus (sem permissão para ninguém) ────────────────────────────────
INSERT INTO public.app_menu (modulo_id, codigo, nome, rota, ordem, ativo)
SELECT m.id, 'encarregados_conferencia_ponto', 'Conferência de Ponto', '/app/encarregados/conferencia-ponto', 15, true
  FROM public.app_modulo m WHERE m.codigo = 'encarregados'
ON CONFLICT (modulo_id, codigo) DO NOTHING;

INSERT INTO public.app_menu (modulo_id, codigo, nome, rota, ordem, ativo)
SELECT m.id, 'ponto_receber_encarregados', U&'Ponto \2014 receber/devolver o envio dos encarregados', NULL, 33, true
  FROM public.app_modulo m WHERE m.codigo = 'operacional'
ON CONFLICT (modulo_id, codigo) DO NOTHING;

-- ── 2) Status novo na Conferência de Ponto ───────────────────────────────
ALTER TABLE public."SISTEMA_CONFERENCIA_PONTO" DROP CONSTRAINT IF EXISTS scp_status_conhecido;
ALTER TABLE public."SISTEMA_CONFERENCIA_PONTO" ADD CONSTRAINT scp_status_conhecido CHECK (status IN (
  'Pendente Encarregados',
  'Pendente Operacional', 'Em Andamento Operacional',
  'Pendente RH', 'Em Andamento RH', 'Conferido RH',
  'Liberado Financeiro', 'Pago',
  'Devolvido Operacional', 'Devolvido RH', 'Problema'
));

-- ── 3) Quem é quem ───────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.ponto_enc_eh_encarregado()
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public, pg_temp AS $$
  SELECT public.can_access(auth.uid(), 'encarregados_conferencia_ponto', 'visualizar'::public.app_acao)
$$;
CREATE OR REPLACE FUNCTION public.ponto_enc_eh_operacional()
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public, pg_temp AS $$
  SELECT public.can_access(auth.uid(), 'ponto_receber_encarregados', 'visualizar'::public.app_acao)
      OR public.can_access(auth.uid(), 'operacional_conferencia_ponto', 'visualizar'::public.app_acao)
      OR public.can_access(auth.uid(), 'rh_conferencia_ponto', 'visualizar'::public.app_acao)
$$;
CREATE OR REPLACE FUNCTION public.ponto_enc_pode_receber()
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public, pg_temp AS $$
  SELECT public.can_access(auth.uid(), 'ponto_receber_encarregados', 'visualizar'::public.app_acao)
$$;
REVOKE ALL ON FUNCTION public.ponto_enc_eh_encarregado(), public.ponto_enc_eh_operacional(), public.ponto_enc_pode_receber() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.ponto_enc_eh_encarregado(), public.ponto_enc_eh_operacional(), public.ponto_enc_pode_receber() TO authenticated;

-- ── 4) Tabelas ───────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public."PONTO_ENVIO_ENCARREGADO" (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mes_referencia    text   NOT NULL CHECK (mes_referencia ~ '^\d{4}-\d{2}$'),
  contrato_empresa  bigint NOT NULL,
  contrato_filial   bigint NOT NULL,
  contrato_nome     text,
  posto             text   NOT NULL DEFAULT '',   -- recorte opcional ('' = contrato todo)
  encarregado_id    uuid   NOT NULL DEFAULT auth.uid(),
  encarregado_nome  text,
  status            text   NOT NULL DEFAULT 'rascunho'
                      CHECK (status IN ('rascunho', 'enviado', 'devolvido', 'recebido')),
  observacao        text,
  enviado_em        timestamptz,
  recebido_por      text, recebido_em timestamptz,
  devolvido_por     text, devolvido_em timestamptz, devolucao_motivo text,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now(),
  -- Um envio por encarregado, contrato, posto e mês (posto '' = contrato todo).
  CONSTRAINT pee_unico UNIQUE (mes_referencia, contrato_empresa, contrato_filial, encarregado_id, posto)
);
CREATE INDEX IF NOT EXISTS idx_pee_mes_contrato ON public."PONTO_ENVIO_ENCARREGADO"(mes_referencia, contrato_empresa, contrato_filial);
CREATE INDEX IF NOT EXISTS idx_pee_encarregado ON public."PONTO_ENVIO_ENCARREGADO"(encarregado_id);

DROP TRIGGER IF EXISTS trg_pee_updated ON public."PONTO_ENVIO_ENCARREGADO";
CREATE TRIGGER trg_pee_updated BEFORE UPDATE ON public."PONTO_ENVIO_ENCARREGADO"
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE IF NOT EXISTS public."PONTO_ENVIO_ITEM" (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  envio_id       bigint NOT NULL REFERENCES public."PONTO_ENVIO_ENCARREGADO"(id) ON DELETE CASCADE,
  empregado_id   bigint,
  nome           text NOT NULL,
  cadastro       bigint,
  cargo          text,
  posto          text,
  situacao       text NOT NULL DEFAULT 'ok'
                   CHECK (situacao IN ('ok', 'faltas', 'atestado', 'ferias', 'afastado', 'desligado', 'divergencia')),
  faltas         integer NOT NULL DEFAULT 0 CHECK (faltas >= 0),
  atrasos        integer NOT NULL DEFAULT 0 CHECK (atrasos >= 0),
  horas_extras   text,
  dias_marcados  integer,             -- foto do relógio no envio
  dias_sem_marcacao integer,
  observacao     text,
  CONSTRAINT pei_unico UNIQUE (envio_id, empregado_id)
);
CREATE INDEX IF NOT EXISTS idx_pei_envio ON public."PONTO_ENVIO_ITEM"(envio_id);

CREATE TABLE IF NOT EXISTS public."PONTO_ENVIO_ANEXO" (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  envio_id      bigint NOT NULL REFERENCES public."PONTO_ENVIO_ENCARREGADO"(id) ON DELETE CASCADE,
  storage_path  text NOT NULL,
  nome_arquivo  text,
  mime_type     text,
  tamanho_bytes bigint,
  created_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_pea_envio ON public."PONTO_ENVIO_ANEXO"(envio_id);

CREATE TABLE IF NOT EXISTS public."PONTO_ENVIO_EVENTO" (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  envio_id    bigint NOT NULL REFERENCES public."PONTO_ENVIO_ENCARREGADO"(id) ON DELETE CASCADE,
  acao        text NOT NULL,          -- criado | salvo | enviado | recebido | devolvido
  de_status   text,
  para_status text,
  observacao  text,
  autor_id    uuid DEFAULT auth.uid(),
  autor_nome  text,
  created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_pev_envio ON public."PONTO_ENVIO_EVENTO"(envio_id, created_at);

-- ── 5) RLS: leitura direta; escrita só pelas RPCs ────────────────────────
CREATE OR REPLACE FUNCTION public.ponto_enc_pode_ver(_envio bigint)
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public, pg_temp AS $$
  SELECT EXISTS (
    SELECT 1 FROM public."PONTO_ENVIO_ENCARREGADO" e
     WHERE e.id = _envio
       AND ((e.encarregado_id = auth.uid() AND public.ponto_enc_eh_encarregado())
            OR (e.status <> 'rascunho' AND public.ponto_enc_eh_operacional())))
$$;
REVOKE ALL ON FUNCTION public.ponto_enc_pode_ver(bigint) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.ponto_enc_pode_ver(bigint) TO authenticated;

ALTER TABLE public."PONTO_ENVIO_ENCARREGADO" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."PONTO_ENVIO_ITEM"        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."PONTO_ENVIO_ANEXO"       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."PONTO_ENVIO_EVENTO"      ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."PONTO_ENVIO_ENCARREGADO", public."PONTO_ENVIO_ITEM", public."PONTO_ENVIO_ANEXO", public."PONTO_ENVIO_EVENTO" FROM PUBLIC, anon;
GRANT SELECT ON public."PONTO_ENVIO_ENCARREGADO", public."PONTO_ENVIO_ITEM", public."PONTO_ENVIO_ANEXO", public."PONTO_ENVIO_EVENTO" TO authenticated;

DROP POLICY IF EXISTS pee_sel ON public."PONTO_ENVIO_ENCARREGADO";
CREATE POLICY pee_sel ON public."PONTO_ENVIO_ENCARREGADO" FOR SELECT TO authenticated
  USING ((encarregado_id = auth.uid() AND public.ponto_enc_eh_encarregado())
         OR (status <> 'rascunho' AND public.ponto_enc_eh_operacional()));
DROP POLICY IF EXISTS pei_sel ON public."PONTO_ENVIO_ITEM";
CREATE POLICY pei_sel ON public."PONTO_ENVIO_ITEM" FOR SELECT TO authenticated USING (public.ponto_enc_pode_ver(envio_id));
DROP POLICY IF EXISTS pea_sel ON public."PONTO_ENVIO_ANEXO";
CREATE POLICY pea_sel ON public."PONTO_ENVIO_ANEXO" FOR SELECT TO authenticated USING (public.ponto_enc_pode_ver(envio_id));
DROP POLICY IF EXISTS pev_sel ON public."PONTO_ENVIO_EVENTO";
CREATE POLICY pev_sel ON public."PONTO_ENVIO_EVENTO" FOR SELECT TO authenticated USING (public.ponto_enc_pode_ver(envio_id));

-- ── 6) Storage das folhas de ponto ───────────────────────────────────────
-- Caminho: <envio_id>/<arquivo>. Quem vê o envio vê o arquivo; só o dono,
-- com o envio editável, sobe ou apaga.
INSERT INTO storage.buckets (id, name, public, file_size_limit)
VALUES ('ponto-encarregados', 'ponto-encarregados', false, 20971520)   -- 20 MB
ON CONFLICT (id) DO NOTHING;

CREATE OR REPLACE FUNCTION public.ponto_enc_pode_editar(_envio bigint)
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public, pg_temp AS $$
  SELECT EXISTS (SELECT 1 FROM public."PONTO_ENVIO_ENCARREGADO" e
                  WHERE e.id = _envio AND e.encarregado_id = auth.uid()
                    AND e.status IN ('rascunho', 'devolvido') AND public.ponto_enc_eh_encarregado())
$$;
REVOKE ALL ON FUNCTION public.ponto_enc_pode_editar(bigint) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.ponto_enc_pode_editar(bigint) TO authenticated;

-- O 1º segmento do caminho é o id do envio; texto que não é número não casa.
CREATE OR REPLACE FUNCTION public.ponto_enc_envio_do_caminho(_nome text)
RETURNS bigint LANGUAGE sql IMMUTABLE SET search_path = public, pg_temp AS $$
  SELECT CASE WHEN split_part(_nome, '/', 1) ~ '^[0-9]{1,18}$' THEN split_part(_nome, '/', 1)::bigint END
$$;

DROP POLICY IF EXISTS "ponto enc anexo select" ON storage.objects;
CREATE POLICY "ponto enc anexo select" ON storage.objects FOR SELECT TO authenticated
  USING (bucket_id = 'ponto-encarregados' AND public.ponto_enc_pode_ver(public.ponto_enc_envio_do_caminho(name)));
DROP POLICY IF EXISTS "ponto enc anexo insert" ON storage.objects;
CREATE POLICY "ponto enc anexo insert" ON storage.objects FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'ponto-encarregados' AND public.ponto_enc_pode_editar(public.ponto_enc_envio_do_caminho(name)));
DROP POLICY IF EXISTS "ponto enc anexo delete" ON storage.objects;
CREATE POLICY "ponto enc anexo delete" ON storage.objects FOR DELETE TO authenticated
  USING (bucket_id = 'ponto-encarregados' AND public.ponto_enc_pode_editar(public.ponto_enc_envio_do_caminho(name)));

-- ── 7) Contexto do encarregado: ele mesmo e os contratos ─────────────────
CREATE OR REPLACE FUNCTION public.ponto_enc_contexto()
RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public, pg_temp AS $$
BEGIN
  IF NOT (public.ponto_enc_eh_encarregado() OR public.ponto_enc_eh_operacional()) THEN
    RAISE EXCEPTION 'Sem acesso à Conferência de Ponto dos encarregados.' USING ERRCODE = '42501';
  END IF;
  RETURN jsonb_build_object(
    'eu', (SELECT jsonb_build_object('nome', e."Nome", 'empresa', e."Empresa", 'filial', e."Filial", 'posto', e."Nome do Posto")
             FROM public."EMPREGADOS" e WHERE e.auth_user_id = auth.uid()
            ORDER BY (e."Situação" = 'Trabalhando') DESC, e."ID" DESC LIMIT 1),
    'contratos', COALESCE((SELECT jsonb_agg(jsonb_build_object('empresa', c."Empresa", 'filial', c."Filial",
                    'nome', c."NOME CONTRATO", 'empresa_nome', c."NOME EMPRESA") ORDER BY c."NOME CONTRATO")
                    FROM public."CONTRATOS" c WHERE c."ATIVO" = 'SIM'), '[]'::jsonb),
    'relogio_ate', public.diaria_ponto_sincronizado_ate());
END $$;
REVOKE ALL ON FUNCTION public.ponto_enc_contexto() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.ponto_enc_contexto() TO authenticated;

-- ── 8) Colaboradores do contrato + o que o relógio viu no mês ────────────
-- dias_marcados = dias com ao menos uma batida; dias_uteis_sem_marcacao =
-- seg–sex do mês (até o último dia que o relógio já tem) sem batida.
CREATE OR REPLACE FUNCTION public.ponto_enc_colaboradores(p_empresa bigint, p_filial bigint, p_mes text)
RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public, pg_temp AS $fn$
DECLARE
  v_de  date;
  v_ate date;
  v_lim date;
  v_relogio jsonb := '{}'::jsonb;
BEGIN
  IF NOT (public.ponto_enc_eh_encarregado() OR public.ponto_enc_eh_operacional()) THEN
    RAISE EXCEPTION 'Sem acesso à Conferência de Ponto dos encarregados.' USING ERRCODE = '42501';
  END IF;
  IF p_mes !~ '^\d{4}-\d{2}$' THEN RAISE EXCEPTION 'Mês inválido.'; END IF;
  v_de  := (p_mes || '-01')::date;
  v_ate := (v_de + interval '1 month')::date - 1;
  v_lim := LEAST(v_ate, COALESCE(public.diaria_ponto_sincronizado_ate(), v_de - 1));

  IF to_regclass('espelho."BiMarcacoes"') IS NOT NULL AND v_lim >= v_de THEN
    BEGIN
      EXECUTE $q$
        SELECT COALESCE(jsonb_object_agg(cad::text, jsonb_build_object('dias', dias)), '{}'::jsonb)
          FROM (SELECT (m.matricula % 100000000) AS cad, array_agg(DISTINCT m.data_hora::date) AS dias
                  FROM espelho."BiMarcacoes" m
                 WHERE m.empresa = $1 AND m.data_hora >= $2 AND m.data_hora < $3 + 1
                 GROUP BY 1) x
      $q$ INTO v_relogio USING p_empresa::int, v_de, v_lim;
    EXCEPTION WHEN OTHERS THEN v_relogio := '{}'::jsonb;
    END;
  END IF;

  RETURN jsonb_build_object(
    'de', v_de, 'ate', v_ate, 'relogio_ate', CASE WHEN v_lim >= v_de THEN v_lim END,
    'colaboradores', COALESCE((
      SELECT jsonb_agg(jsonb_build_object(
               'empregado_id', e."ID", 'nome', e."Nome", 'cadastro', e."Cadastro", 'cargo', e."Título do Cargo",
               'posto', e."Nome do Posto", 'situacao_senior', e."Situação",
               'dias_marcados', COALESCE(jsonb_array_length(v_relogio -> (e."Cadastro"::text) -> 'dias'), 0),
               'dias_uteis_sem_marcacao', CASE WHEN v_lim >= v_de THEN (
                  SELECT count(*) FROM generate_series(v_de, v_lim, interval '1 day') g
                   WHERE extract(isodow FROM g) < 6
                     AND NOT COALESCE((v_relogio -> (e."Cadastro"::text) -> 'dias') ? to_char(g, 'YYYY-MM-DD'), false)) END)
             ORDER BY e."Nome")
        FROM public."EMPREGADOS" e
       WHERE e."Empresa" = p_empresa AND e."Filial" = p_filial
         AND COALESCE(e."Situação", '') <> 'Demitido'
         AND COALESCE(e."Nome", '') NOT ILIKE '%teste%'), '[]'::jsonb));
END $fn$;
REVOKE ALL ON FUNCTION public.ponto_enc_colaboradores(bigint, bigint, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.ponto_enc_colaboradores(bigint, bigint, text) TO authenticated;

-- ── 9) Salvar o rascunho (cabeçalho + itens) ─────────────────────────────
CREATE OR REPLACE FUNCTION public.ponto_enc_salvar(p jsonb)
RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $fn$
DECLARE
  v_id    bigint := NULLIF(p->>'id', '')::bigint;
  v_env   public."PONTO_ENVIO_ENCARREGADO"%ROWTYPE;
  v_nome  text := (SELECT coalesce(display_name, email) FROM public.profiles WHERE id = auth.uid());
  v_mes   text := p->>'mes_referencia';
  v_emp   bigint := (p->>'contrato_empresa')::bigint;
  v_fil   bigint := (p->>'contrato_filial')::bigint;
  v_posto text := COALESCE(btrim(p->>'posto'), '');
BEGIN
  IF NOT public.ponto_enc_eh_encarregado() THEN
    RAISE EXCEPTION 'Sem acesso para enviar ponto.' USING ERRCODE = '42501';
  END IF;

  IF v_id IS NULL THEN
    IF v_mes !~ '^\d{4}-\d{2}$' OR v_emp IS NULL OR v_fil IS NULL THEN
      RAISE EXCEPTION 'Informe o mês e o contrato.';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM public."CONTRATOS" WHERE "Empresa" = v_emp AND "Filial" = v_fil AND "ATIVO" = 'SIM') THEN
      RAISE EXCEPTION 'Contrato não encontrado entre os ativos.';
    END IF;
    SELECT * INTO v_env FROM public."PONTO_ENVIO_ENCARREGADO"
     WHERE mes_referencia = v_mes AND contrato_empresa = v_emp AND contrato_filial = v_fil
       AND encarregado_id = auth.uid() AND posto = v_posto;
    IF NOT FOUND THEN
      INSERT INTO public."PONTO_ENVIO_ENCARREGADO"
        (mes_referencia, contrato_empresa, contrato_filial, contrato_nome, posto, encarregado_id, encarregado_nome, observacao)
      VALUES (v_mes, v_emp, v_fil,
              (SELECT "NOME CONTRATO" FROM public."CONTRATOS" WHERE "Empresa" = v_emp AND "Filial" = v_fil AND "ATIVO" = 'SIM' LIMIT 1),
              v_posto, auth.uid(), v_nome, NULLIF(btrim(p->>'observacao'), ''))
      RETURNING * INTO v_env;
      INSERT INTO public."PONTO_ENVIO_EVENTO" (envio_id, acao, para_status, autor_nome)
      VALUES (v_env.id, 'criado', 'rascunho', v_nome);
    END IF;
    v_id := v_env.id;
  ELSE
    SELECT * INTO v_env FROM public."PONTO_ENVIO_ENCARREGADO" WHERE id = v_id FOR UPDATE;
    IF NOT FOUND OR v_env.encarregado_id <> auth.uid() THEN RAISE EXCEPTION 'Envio não encontrado.'; END IF;
  END IF;

  IF v_env.status NOT IN ('rascunho', 'devolvido') THEN
    RAISE EXCEPTION 'Este envio já foi % — não dá mais para alterar.', v_env.status;
  END IF;

  UPDATE public."PONTO_ENVIO_ENCARREGADO" SET observacao = NULLIF(btrim(p->>'observacao'), '') WHERE id = v_id;

  IF p ? 'itens' THEN
    DELETE FROM public."PONTO_ENVIO_ITEM" WHERE envio_id = v_id;
    INSERT INTO public."PONTO_ENVIO_ITEM"
      (envio_id, empregado_id, nome, cadastro, cargo, posto, situacao, faltas, atrasos, horas_extras, dias_marcados, dias_sem_marcacao, observacao)
    SELECT v_id, NULLIF(i->>'empregado_id', '')::bigint, btrim(i->>'nome'), NULLIF(i->>'cadastro', '')::bigint,
           NULLIF(i->>'cargo', ''), NULLIF(i->>'posto', ''), COALESCE(NULLIF(i->>'situacao', ''), 'ok'),
           GREATEST(COALESCE(NULLIF(i->>'faltas', '')::int, 0), 0), GREATEST(COALESCE(NULLIF(i->>'atrasos', '')::int, 0), 0),
           NULLIF(btrim(i->>'horas_extras'), ''), NULLIF(i->>'dias_marcados', '')::int, NULLIF(i->>'dias_sem_marcacao', '')::int,
           NULLIF(btrim(i->>'observacao'), '')
      FROM jsonb_array_elements(p->'itens') AS i
     WHERE btrim(coalesce(i->>'nome', '')) <> '';
  END IF;
  RETURN v_id;
END $fn$;
REVOKE ALL ON FUNCTION public.ponto_enc_salvar(jsonb) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.ponto_enc_salvar(jsonb) TO authenticated;

-- ── 10) Anexos ───────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.ponto_enc_anexo_registrar(p_envio bigint, p_path text, p_nome text, p_mime text, p_tamanho bigint)
RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$
DECLARE v_id bigint;
BEGIN
  IF NOT public.ponto_enc_pode_editar(p_envio) THEN RAISE EXCEPTION 'Envio não editável.' USING ERRCODE = '42501'; END IF;
  IF public.ponto_enc_envio_do_caminho(p_path) IS DISTINCT FROM p_envio THEN RAISE EXCEPTION 'Caminho do arquivo inválido.'; END IF;
  INSERT INTO public."PONTO_ENVIO_ANEXO" (envio_id, storage_path, nome_arquivo, mime_type, tamanho_bytes)
  VALUES (p_envio, p_path, p_nome, p_mime, p_tamanho) RETURNING id INTO v_id;
  RETURN v_id;
END $$;
CREATE OR REPLACE FUNCTION public.ponto_enc_anexo_remover(p_id bigint)
RETURNS text LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$
DECLARE v record;
BEGIN
  SELECT * INTO v FROM public."PONTO_ENVIO_ANEXO" WHERE id = p_id;
  IF NOT FOUND OR NOT public.ponto_enc_pode_editar(v.envio_id) THEN RAISE EXCEPTION 'Anexo não editável.' USING ERRCODE = '42501'; END IF;
  DELETE FROM public."PONTO_ENVIO_ANEXO" WHERE id = p_id;
  RETURN v.storage_path;   -- a tela apaga o arquivo do bucket
END $$;
REVOKE ALL ON FUNCTION public.ponto_enc_anexo_registrar(bigint, text, text, text, bigint), public.ponto_enc_anexo_remover(bigint) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.ponto_enc_anexo_registrar(bigint, text, text, text, bigint), public.ponto_enc_anexo_remover(bigint) TO authenticated;

-- ── 11) Enviar ao Operacional ────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.ponto_enc_enviar(p_id bigint)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $fn$
DECLARE
  v_env  public."PONTO_ENVIO_ENCARREGADO"%ROWTYPE;
  v_nome text := (SELECT coalesce(display_name, email) FROM public.profiles WHERE id = auth.uid());
  v_scp  public."SISTEMA_CONFERENCIA_PONTO"%ROWTYPE;
BEGIN
  SELECT * INTO v_env FROM public."PONTO_ENVIO_ENCARREGADO" WHERE id = p_id FOR UPDATE;
  IF NOT FOUND OR v_env.encarregado_id <> auth.uid() OR NOT public.ponto_enc_eh_encarregado() THEN
    RAISE EXCEPTION 'Envio não encontrado.' USING ERRCODE = '42501';
  END IF;
  IF v_env.status NOT IN ('rascunho', 'devolvido') THEN RAISE EXCEPTION 'Este envio já foi %.', v_env.status; END IF;
  IF NOT EXISTS (SELECT 1 FROM public."PONTO_ENVIO_ITEM" WHERE envio_id = p_id) THEN
    RAISE EXCEPTION 'Confira ao menos um colaborador antes de enviar.';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public."PONTO_ENVIO_ANEXO" WHERE envio_id = p_id) THEN
    RAISE EXCEPTION 'Anexe a folha/espelho de ponto antes de enviar.';
  END IF;

  UPDATE public."PONTO_ENVIO_ENCARREGADO"
     SET status = 'enviado', enviado_em = now(), devolucao_motivo = NULL
   WHERE id = p_id;
  INSERT INTO public."PONTO_ENVIO_EVENTO" (envio_id, acao, de_status, para_status, autor_nome)
  VALUES (p_id, 'enviado', v_env.status, 'enviado', v_nome);

  -- A linha do contrato na Conferência de Ponto sai de "Pendente
  -- Encarregados" (ou nasce) em "Pendente Operacional". Se o Operacional já
  -- andou com ela, não mexe.
  SELECT * INTO v_scp FROM public."SISTEMA_CONFERENCIA_PONTO"
   WHERE contrato_empresa = v_env.contrato_empresa AND contrato_filial = v_env.contrato_filial
     AND mes_referencia = v_env.mes_referencia FOR UPDATE;
  IF NOT FOUND THEN
    INSERT INTO public."SISTEMA_CONFERENCIA_PONTO" (contrato_empresa, contrato_filial, contrato_nome, mes_referencia, status, atualizado_por)
    VALUES (v_env.contrato_empresa, v_env.contrato_filial, v_env.contrato_nome, v_env.mes_referencia, 'Pendente Operacional', v_nome)
    RETURNING * INTO v_scp;
    INSERT INTO public."SISTEMA_CONFERENCIA_PONTO_EVENTOS" (conferencia_id, acao, de_status, para_status, observacao, usuario_nome)
    VALUES (v_scp.id, 'envio_encarregado', 'Pendente Encarregados', 'Pendente Operacional', 'Ponto enviado pelo encarregado ' || coalesce(v_nome, ''), v_nome);
  ELSIF v_scp.status = 'Pendente Encarregados' THEN
    UPDATE public."SISTEMA_CONFERENCIA_PONTO" SET status = 'Pendente Operacional', atualizado_por = v_nome WHERE id = v_scp.id;
    INSERT INTO public."SISTEMA_CONFERENCIA_PONTO_EVENTOS" (conferencia_id, acao, de_status, para_status, observacao, usuario_nome)
    VALUES (v_scp.id, 'envio_encarregado', 'Pendente Encarregados', 'Pendente Operacional', 'Ponto enviado pelo encarregado ' || coalesce(v_nome, ''), v_nome);
  ELSE
    INSERT INTO public."SISTEMA_CONFERENCIA_PONTO_EVENTOS" (conferencia_id, acao, de_status, para_status, observacao, usuario_nome)
    VALUES (v_scp.id, 'envio_encarregado', v_scp.status, v_scp.status, 'Ponto (re)enviado pelo encarregado ' || coalesce(v_nome, ''), v_nome);
  END IF;
END $fn$;
REVOKE ALL ON FUNCTION public.ponto_enc_enviar(bigint) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.ponto_enc_enviar(bigint) TO authenticated;

-- ── 12) Operacional: receber ou devolver ─────────────────────────────────
CREATE OR REPLACE FUNCTION public.ponto_enc_decidir(p_id bigint, p_acao text, p_motivo text DEFAULT NULL)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $fn$
DECLARE
  v_env  public."PONTO_ENVIO_ENCARREGADO"%ROWTYPE;
  v_nome text := (SELECT coalesce(display_name, email) FROM public.profiles WHERE id = auth.uid());
  v_mot  text := NULLIF(btrim(coalesce(p_motivo, '')), '');
BEGIN
  IF NOT public.ponto_enc_pode_receber() THEN
    RAISE EXCEPTION 'Sem permissão para receber/devolver o ponto dos encarregados.' USING ERRCODE = '42501';
  END IF;
  SELECT * INTO v_env FROM public."PONTO_ENVIO_ENCARREGADO" WHERE id = p_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Envio não encontrado.'; END IF;
  IF v_env.status <> 'enviado' THEN RAISE EXCEPTION 'Só envio "enviado" pode ser recebido ou devolvido (está %).', v_env.status; END IF;

  IF p_acao = 'receber' THEN
    UPDATE public."PONTO_ENVIO_ENCARREGADO" SET status = 'recebido', recebido_por = v_nome, recebido_em = now() WHERE id = p_id;
    INSERT INTO public."PONTO_ENVIO_EVENTO" (envio_id, acao, de_status, para_status, observacao, autor_nome)
    VALUES (p_id, 'recebido', 'enviado', 'recebido', v_mot, v_nome);
  ELSIF p_acao = 'devolver' THEN
    IF v_mot IS NULL THEN RAISE EXCEPTION 'Informe o motivo da devolução.'; END IF;
    UPDATE public."PONTO_ENVIO_ENCARREGADO"
       SET status = 'devolvido', devolvido_por = v_nome, devolvido_em = now(), devolucao_motivo = v_mot
     WHERE id = p_id;
    INSERT INTO public."PONTO_ENVIO_EVENTO" (envio_id, acao, de_status, para_status, observacao, autor_nome)
    VALUES (p_id, 'devolvido', 'enviado', 'devolvido', v_mot, v_nome);
    INSERT INTO public.notificacoes (user_id, titulo, mensagem, tipo, link)
    VALUES (v_env.encarregado_id, 'Ponto devolvido pelo Operacional',
            coalesce(v_env.contrato_nome, 'Contrato') || ' — ' || v_env.mes_referencia || '. Motivo: ' || v_mot || '. Corrija e reenvie.',
            'ponto_envio_devolvido', '/app/encarregados/conferencia-ponto?envio=' || p_id);
  ELSE
    RAISE EXCEPTION 'Ação inválida.';
  END IF;
END $fn$;
REVOKE ALL ON FUNCTION public.ponto_enc_decidir(bigint, text, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.ponto_enc_decidir(bigint, text, text) TO authenticated;

NOTIFY pgrst, 'reload schema';

-- ROLLBACK
-- DROP FUNCTION IF EXISTS public.ponto_enc_decidir(bigint, text, text);
-- DROP FUNCTION IF EXISTS public.ponto_enc_enviar(bigint);
-- DROP FUNCTION IF EXISTS public.ponto_enc_anexo_remover(bigint);
-- DROP FUNCTION IF EXISTS public.ponto_enc_anexo_registrar(bigint, text, text, text, bigint);
-- DROP FUNCTION IF EXISTS public.ponto_enc_salvar(jsonb);
-- DROP FUNCTION IF EXISTS public.ponto_enc_colaboradores(bigint, bigint, text);
-- DROP FUNCTION IF EXISTS public.ponto_enc_contexto();
-- DROP POLICY IF EXISTS "ponto enc anexo select" ON storage.objects;
-- DROP POLICY IF EXISTS "ponto enc anexo insert" ON storage.objects;
-- DROP POLICY IF EXISTS "ponto enc anexo delete" ON storage.objects;
-- DROP TABLE IF EXISTS public."PONTO_ENVIO_EVENTO", public."PONTO_ENVIO_ANEXO", public."PONTO_ENVIO_ITEM", public."PONTO_ENVIO_ENCARREGADO";
-- DROP FUNCTION IF EXISTS public.ponto_enc_envio_do_caminho(text), public.ponto_enc_pode_editar(bigint), public.ponto_enc_pode_ver(bigint),
--   public.ponto_enc_pode_receber(), public.ponto_enc_eh_operacional(), public.ponto_enc_eh_encarregado();
-- (status) UPDATE "SISTEMA_CONFERENCIA_PONTO" SET status = 'Pendente Operacional' WHERE status = 'Pendente Encarregados'; e recriar o CHECK sem ele.
-- DELETE FROM public.app_menu WHERE codigo IN ('encarregados_conferencia_ponto', 'ponto_receber_encarregados');
