-- =========================================================================
-- Conferência de Ponto: etiqueta "Conferindo" por contrato (01/10/2026)
--
-- PEDIDO (Pablo): "um botão que o usuário clique em CONFERINDO, só pra
-- ficar com um status ali tipo uma etiqueta que o usuário está conferindo;
-- ao clicar no card da etiqueta aparecem as opções e observação".
--
-- MODELO
--   Tabela à parte, uma etiqueta por contrato no mês — a mesma chave da
--   SISTEMA_CONFERENCIA_PONTO (mes_referencia, contrato_empresa,
--   contrato_filial). Não mexe no status do fluxo e não cria linha lá: o
--   contrato sem linha (ninguém agiu ainda) também pode ser etiquetado.
--   Quem marcou fica gravado (nome + id); qualquer um das três telas pode
--   trocar ou tirar — é recado entre a equipe, não trava.
--   Quando alguém AGE no contrato (aprova, confirma, paga, devolve), a tela
--   tira a etiqueta: a conferência daquela etapa acabou.
--
-- ACESSO: quem abre qualquer Conferência de Ponto (RH, Operacional,
-- Financeiro) lê e escreve.
--
-- Realtime ligado: a etiqueta aparece para os outros sem recarregar.
--
-- Idempotente. Aplicar no banco do app. ROLLBACK no fim.
-- =========================================================================

CREATE TABLE IF NOT EXISTS public."SISTEMA_CONFERENCIA_PONTO_ETIQUETA" (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mes_referencia   text   NOT NULL,
  contrato_empresa bigint NOT NULL,
  contrato_filial  bigint NOT NULL,
  tipo             text   NOT NULL DEFAULT 'conferindo',  -- código; o rótulo é da tela
  observacao       text,
  modulo           text,
  por_id           uuid   DEFAULT auth.uid(),
  por_nome         text,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT scp_etiqueta_unica UNIQUE (mes_referencia, contrato_empresa, contrato_filial),
  CONSTRAINT scp_etiqueta_tipo CHECK (tipo IN ('conferindo', 'aguardando_documentos', 'divergencia', 'conferido')),
  CONSTRAINT scp_etiqueta_modulo CHECK (modulo IS NULL OR modulo IN ('operacional', 'rh', 'financeiro'))
);
CREATE INDEX IF NOT EXISTS idx_scp_etiqueta_mes ON public."SISTEMA_CONFERENCIA_PONTO_ETIQUETA"(mes_referencia);

DROP TRIGGER IF EXISTS trg_scp_etiqueta_updated_at ON public."SISTEMA_CONFERENCIA_PONTO_ETIQUETA";
CREATE TRIGGER trg_scp_etiqueta_updated_at
  BEFORE UPDATE ON public."SISTEMA_CONFERENCIA_PONTO_ETIQUETA"
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- Quem grava é sempre quem está logado (a tela manda o nome, o banco o id).
CREATE OR REPLACE FUNCTION public.scp_etiqueta_autor()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$
BEGIN
  NEW.por_id := auth.uid();
  IF NEW.por_nome IS NULL OR btrim(NEW.por_nome) = '' THEN
    SELECT coalesce(display_name, email) INTO NEW.por_nome FROM public.profiles WHERE id = auth.uid();
  END IF;
  RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS trg_scp_etiqueta_autor ON public."SISTEMA_CONFERENCIA_PONTO_ETIQUETA";
CREATE TRIGGER trg_scp_etiqueta_autor
  BEFORE INSERT OR UPDATE ON public."SISTEMA_CONFERENCIA_PONTO_ETIQUETA"
  FOR EACH ROW EXECUTE FUNCTION public.scp_etiqueta_autor();

ALTER TABLE public."SISTEMA_CONFERENCIA_PONTO_ETIQUETA" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."SISTEMA_CONFERENCIA_PONTO_ETIQUETA" FROM PUBLIC, anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."SISTEMA_CONFERENCIA_PONTO_ETIQUETA" TO authenticated;

DROP POLICY IF EXISTS scp_etiqueta_gate ON public."SISTEMA_CONFERENCIA_PONTO_ETIQUETA";
CREATE POLICY scp_etiqueta_gate ON public."SISTEMA_CONFERENCIA_PONTO_ETIQUETA" FOR ALL TO authenticated
  USING (
    (select public.can_access(auth.uid(), 'rh_conferencia_ponto', 'visualizar'::app_acao))
    OR (select public.can_access(auth.uid(), 'operacional_conferencia_ponto', 'visualizar'::app_acao))
    OR (select public.can_access(auth.uid(), 'financeiro_conferencia_ponto', 'visualizar'::app_acao))
  )
  WITH CHECK (
    (select public.can_access(auth.uid(), 'rh_conferencia_ponto', 'visualizar'::app_acao))
    OR (select public.can_access(auth.uid(), 'operacional_conferencia_ponto', 'visualizar'::app_acao))
    OR (select public.can_access(auth.uid(), 'financeiro_conferencia_ponto', 'visualizar'::app_acao))
  );

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables
                  WHERE pubname = 'supabase_realtime' AND tablename = 'SISTEMA_CONFERENCIA_PONTO_ETIQUETA') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public."SISTEMA_CONFERENCIA_PONTO_ETIQUETA";
  END IF;
END $$;

NOTIFY pgrst, 'reload schema';

-- =========================================================================
-- ROLLBACK
-- =========================================================================
-- ALTER PUBLICATION supabase_realtime DROP TABLE public."SISTEMA_CONFERENCIA_PONTO_ETIQUETA";
-- DROP TABLE IF EXISTS public."SISTEMA_CONFERENCIA_PONTO_ETIQUETA";
-- DROP FUNCTION IF EXISTS public.scp_etiqueta_autor();
-- NOTIFY pgrst, 'reload schema';
