-- =========================================================================
-- RH › ATIVOS/CONTRATOS — OBSERVAÇÕES (08/10/2026)
--
-- PEDIDO (Pablo): "opção de colocar observação no Ativos/Contratos, pra
-- colocar por que tem mais pessoas em tal contrato etc".
--
-- Uma observação é um recado datado e assinado, no CONTRATO inteiro ou num
-- POSTO da planilha (posto '' = o contrato todo). Vários por contrato —
-- vira o histórico de "por que está assim" (cobertura de férias, reforço
-- pedido pelo cliente, aditivo em andamento…). Ninguém edita o texto dos
-- outros: quem escreveu apaga o seu; quem vincula postos
-- (rh_ativos_contratos_vincular) pode apagar qualquer um. Apagar é lógico.
--
-- Acesso: ver e escrever = rh_ativos_contratos (o mesmo da tela).
-- Idempotente. Aplicar no banco do app.
-- =========================================================================

CREATE TABLE IF NOT EXISTS public."RH_AC_OBSERVACAO" (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contrato_id uuid NOT NULL REFERENCES public.contratos(id) ON DELETE CASCADE,
  posto       text NOT NULL DEFAULT '',          -- '' = contrato inteiro
  texto       text NOT NULL CHECK (length(btrim(texto)) BETWEEN 3 AND 2000),
  autor_id    uuid NOT NULL DEFAULT auth.uid(),
  autor_nome  text,
  created_at  timestamptz NOT NULL DEFAULT now(),
  excluida_em timestamptz,
  excluida_por text
);
CREATE INDEX IF NOT EXISTS idx_rh_ac_obs_contrato ON public."RH_AC_OBSERVACAO"(contrato_id, created_at DESC) WHERE excluida_em IS NULL;

ALTER TABLE public."RH_AC_OBSERVACAO" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."RH_AC_OBSERVACAO" FROM PUBLIC, anon;
GRANT SELECT ON public."RH_AC_OBSERVACAO" TO authenticated;
DROP POLICY IF EXISTS rh_ac_obs_sel ON public."RH_AC_OBSERVACAO";
CREATE POLICY rh_ac_obs_sel ON public."RH_AC_OBSERVACAO" FOR SELECT TO authenticated
  USING (excluida_em IS NULL AND public.has_screen_access(auth.uid(), 'rh_ativos_contratos', 'visualizar'::public.app_acao));

-- Todas as observações vivas (a tela agrupa por contrato e posto).
CREATE OR REPLACE FUNCTION public.rh_ac_observacoes()
RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public, pg_temp AS $$
DECLARE v_uid uuid := public.rh_ac_exige(false);
BEGIN
  RETURN COALESCE((
    SELECT jsonb_agg(jsonb_build_object(
             'id', o.id, 'contrato_id', o.contrato_id, 'posto', o.posto, 'texto', o.texto,
             'autor_nome', o.autor_nome, 'created_at', o.created_at,
             'pode_apagar', o.autor_id = v_uid OR public.has_screen_access(v_uid, 'rh_ativos_contratos_vincular', 'visualizar'::public.app_acao))
           ORDER BY o.created_at DESC)
      FROM public."RH_AC_OBSERVACAO" o WHERE o.excluida_em IS NULL), '[]'::jsonb);
END $$;
REVOKE ALL ON FUNCTION public.rh_ac_observacoes() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.rh_ac_observacoes() TO authenticated;

CREATE OR REPLACE FUNCTION public.rh_ac_observacao_salvar(p_contrato_id uuid, p_posto text, p_texto text)
RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$
DECLARE
  v_uid  uuid := public.rh_ac_exige(false);
  v_nome text := (SELECT coalesce(display_name, email) FROM public.profiles WHERE id = v_uid);
  v_id   bigint;
BEGIN
  IF length(btrim(coalesce(p_texto, ''))) < 3 THEN RAISE EXCEPTION 'Escreva a observação (mín. 3 caracteres).'; END IF;
  IF NOT EXISTS (SELECT 1 FROM public.contratos WHERE id = p_contrato_id) THEN RAISE EXCEPTION 'Contrato não encontrado.'; END IF;
  INSERT INTO public."RH_AC_OBSERVACAO" (contrato_id, posto, texto, autor_id, autor_nome)
  VALUES (p_contrato_id, btrim(coalesce(p_posto, '')), btrim(p_texto), v_uid, v_nome)
  RETURNING id INTO v_id;
  RETURN v_id;
END $$;
REVOKE ALL ON FUNCTION public.rh_ac_observacao_salvar(uuid, text, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.rh_ac_observacao_salvar(uuid, text, text) TO authenticated;

CREATE OR REPLACE FUNCTION public.rh_ac_observacao_excluir(p_id bigint)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$
DECLARE
  v_uid  uuid := public.rh_ac_exige(false);
  v_nome text := (SELECT coalesce(display_name, email) FROM public.profiles WHERE id = v_uid);
  v_aut  uuid;
BEGIN
  SELECT autor_id INTO v_aut FROM public."RH_AC_OBSERVACAO" WHERE id = p_id AND excluida_em IS NULL;
  IF NOT FOUND THEN RAISE EXCEPTION 'Observação não encontrada.'; END IF;
  IF v_aut <> v_uid AND NOT public.has_screen_access(v_uid, 'rh_ativos_contratos_vincular', 'visualizar'::public.app_acao) THEN
    RAISE EXCEPTION 'Só quem escreveu (ou quem vincula postos) pode apagar esta observação.' USING ERRCODE = '42501';
  END IF;
  UPDATE public."RH_AC_OBSERVACAO" SET excluida_em = now(), excluida_por = v_nome WHERE id = p_id;
END $$;
REVOKE ALL ON FUNCTION public.rh_ac_observacao_excluir(bigint) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.rh_ac_observacao_excluir(bigint) TO authenticated;

NOTIFY pgrst, 'reload schema';

-- ROLLBACK
-- DROP FUNCTION IF EXISTS public.rh_ac_observacao_excluir(bigint), public.rh_ac_observacao_salvar(uuid, text, text), public.rh_ac_observacoes();
-- DROP TABLE IF EXISTS public."RH_AC_OBSERVACAO";
